;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Intermission
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; E1M4: Kitchen Ace (And Taking Names)
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; E1M3: Dark Halls
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; Flash Man
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256 ; Metal Man

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env11,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env0,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env10,@env12,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env5,@env12,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env4,@env11,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env9,@env11,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env8,@env13,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cb,$ca,$c9,$00,$03
@env2:
	.byte $cf,$ce,$cc,$c6,$c1,$c1,$c0,$00,$06
@env3:
	.byte $cf,$04,$c0,$00,$02
@env4:
	.byte $cf,$ce,$cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c3,$c2,$02,$c1,$c1,$c0
	.byte $00,$0f
@env5:
	.byte $cf,$02,$c0,$00,$02
@env6:
	.byte $c3,$c4,$c6,$c8,$c9,$cb,$cc,$ce,$cf,$cb,$ca,$c8,$c6,$c4,$c3,$c3
	.byte $c2,$02,$c1,$03,$c0,$00,$14
@env7:
	.byte $cf,$c0,$00,$01
@env8:
	.byte $cf,$cc,$cb,$ca,$c5,$c4,$c2,$c2,$c1,$c0,$00,$09
@env9:
	.byte $cf,$ce,$cd,$cc,$cb,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5
	.byte $c4,$c4,$c3,$02,$c2,$02,$c1,$03,$c0,$00,$18
@env10:
	.byte $cf,$03,$c0,$00,$02
@env11:
	.byte $c0,$c5,$00,$01
@env12:
	.byte $c0,$bf,$be,$bd,$00,$03
@env13:
	.byte $cc,$c0,$00,$01


; Intermission
@song0ch0:
@ref0:
	.byte $80,$18,$00,$18,$00,$18,$00,$18,$00
@ref1:
	.byte $18,$00,$18,$00,$18,$00,$18,$00
	.byte $ff,$08
	.word @ref1
@ref3:
	.byte $18,$00,$83,$18,$00,$18,$81
@song0ch0loop:
@ref4:
	.byte $80,$1f,$18,$00,$18,$00,$19,$1d,$18,$00,$18,$00,$18,$81
@ref5:
	.byte $25,$19,$23,$19,$1f,$19,$18,$00,$18,$81
@ref6:
	.byte $1f,$18,$00,$18,$00,$19,$1d,$18,$00,$18,$00,$18,$81
@ref7:
	.byte $25,$19,$23,$19,$1e,$85,$18,$00,$18,$81
	.byte $ff,$0d
	.word @ref6
	.byte $ff,$0a
	.word @ref5
	.byte $ff,$0d
	.word @ref6
@ref11:
	.byte $25,$19,$23,$19,$1e,$85,$1c,$00,$1e,$00
@ref12:
	.byte $25,$1e,$00,$1e,$00,$1f,$29,$1e,$00,$1e,$00,$1e,$81
@ref13:
	.byte $2b,$1f,$29,$1f,$25,$1f,$1e,$00,$1e,$81
	.byte $ff,$0d
	.word @ref12
@ref15:
	.byte $2b,$1f,$29,$1f,$24,$85,$1e,$00,$1e,$81
	.byte $ff,$0d
	.word @ref12
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$0d
	.word @ref12
@ref19:
	.byte $2b,$1f,$29,$1f,$25,$1a,$00,$1b,$1c,$81
	.byte $fd
	.word @song0ch0loop

; Intermission
@song0ch1:
@ref20:
	.byte $80,$0a,$00,$0a,$00,$0a,$00,$0a,$00
@ref21:
	.byte $0a,$00,$0a,$00,$0a,$00,$0a,$00
	.byte $ff,$08
	.word @ref21
@ref23:
	.byte $0a,$00,$83,$0a,$00,$0a,$81
@song0ch1loop:
@ref24:
	.byte $80,$11,$0a,$00,$0a,$00,$0b,$0f,$0a,$00,$0a,$00,$0a,$81
@ref25:
	.byte $17,$0b,$15,$0b,$11,$0b,$0a,$00,$0a,$81
@ref26:
	.byte $11,$0a,$00,$0a,$00,$0b,$0f,$0a,$00,$0a,$00,$0a,$81
@ref27:
	.byte $17,$0b,$15,$0b,$10,$85,$0a,$00,$0a,$81
	.byte $ff,$0d
	.word @ref26
	.byte $ff,$0a
	.word @ref25
	.byte $ff,$0d
	.word @ref26
@ref31:
	.byte $17,$0b,$15,$0b,$10,$85,$0e,$00,$10,$00
@ref32:
	.byte $17,$10,$00,$10,$00,$11,$1b,$10,$00,$10,$00,$10,$81
@ref33:
	.byte $1d,$11,$1b,$11,$17,$11,$10,$00,$10,$81
	.byte $ff,$0d
	.word @ref32
@ref35:
	.byte $1d,$11,$1b,$11,$16,$85,$10,$00,$10,$81
	.byte $ff,$0d
	.word @ref32
	.byte $ff,$0a
	.word @ref33
	.byte $ff,$0d
	.word @ref32
@ref39:
	.byte $1d,$11,$1b,$11,$17,$0c,$00,$0d,$0e,$81
	.byte $fd
	.word @song0ch1loop

; Intermission
@song0ch2:
@ref40:
	.byte $8a,$0b,$0b,$0b,$0a,$81
@ref41:
	.byte $0b,$0b,$0b,$0a,$81
	.byte $ff,$05
	.word @ref41
@ref43:
	.byte $0a,$85,$0a,$00,$0a,$81
@song0ch2loop:
@ref44:
	.byte $86,$32,$8a,$10,$86,$32,$8a,$0a,$0a,$00,$86,$32,$8a,$0a,$86,$32
	.byte $8a,$0e,$86,$32,$8a,$0a,$0a,$00,$86,$32,$8a,$0a
@ref45:
	.byte $86,$32,$8a,$16,$86,$32,$8a,$0a,$15,$86,$32,$8a,$0a,$86,$32,$8a
	.byte $10,$0a,$00,$0a,$00,$86,$32,$8a,$0a
	.byte $ff,$10
	.word @ref44
@ref47:
	.byte $86,$32,$8a,$16,$86,$32,$8a,$0a,$15,$86,$32,$8a,$0a,$86,$32,$8a
	.byte $10,$83,$0a,$00,$86,$32,$8a,$0a
	.byte $ff,$10
	.word @ref44
	.byte $ff,$0f
	.word @ref45
	.byte $ff,$10
	.word @ref44
@ref51:
	.byte $86,$32,$8a,$16,$86,$32,$8a,$0a,$15,$86,$32,$8a,$0a,$86,$32,$8a
	.byte $10,$83,$0e,$00,$86,$32,$8a,$10
@ref52:
	.byte $86,$32,$80,$16,$86,$32,$80,$10,$10,$00,$86,$32,$80,$10,$86,$32
	.byte $80,$1a,$86,$32,$80,$10,$10,$00,$86,$32,$80,$10
@ref53:
	.byte $86,$32,$80,$1c,$86,$32,$80,$10,$1b,$86,$32,$80,$10,$86,$32,$80
	.byte $16,$10,$00,$10,$00,$86,$32,$80,$10
	.byte $ff,$10
	.word @ref52
@ref55:
	.byte $86,$32,$80,$1c,$86,$32,$80,$10,$1b,$86,$32,$80,$10,$86,$32,$80
	.byte $16,$83,$10,$00,$86,$32,$80,$10
	.byte $ff,$10
	.word @ref52
	.byte $ff,$0f
	.word @ref53
	.byte $ff,$10
	.word @ref52
@ref59:
	.byte $86,$32,$80,$1c,$86,$32,$80,$10,$1b,$86,$32,$80,$10,$86,$32,$80
	.byte $16,$8a,$0c,$00,$0d,$86,$32,$8a,$0e
	.byte $fd
	.word @song0ch2loop

; Intermission
@song0ch3:
@ref60:
	.byte $84,$0f,$0f,$0f,$0e,$81
@ref61:
	.byte $0f,$0f,$0f,$0e,$81
	.byte $ff,$05
	.word @ref61
@ref63:
	.byte $96,$0d,$00,$89
@song0ch3loop:
@ref64:
	.byte $96,$0c,$85,$94,$0e,$85,$12,$85,$0e,$85
@ref65:
	.byte $12,$85,$0e,$85,$12,$85,$0e,$85
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref64
	.byte $ff,$08
	.word @ref65
	.byte $fd
	.word @song0ch3loop

; Intermission
@song0ch4:
	.byte $fb,$05
@ref80:
	.byte $fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb
	.byte $07,$81,$fb,$04,$81,$fb,$07,$81
	.byte $ff,$08
	.word @ref80
	.byte $ff,$08
	.word @ref80
	.byte $ff,$08
	.word @ref80
@song0ch4loop:
@ref84:
	.byte $fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb
	.byte $07,$81,$fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb,$07,$81,$fb,$04
	.byte $81,$fb,$07,$81,$fb,$04,$81,$fb,$07,$81,$fb,$04,$81,$fb,$07,$81
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $ff,$10
	.word @ref84
	.byte $fd
	.word @song0ch4loop


; E1M4: Kitchen Ace (And Taking Names)
@song1ch0:
@song1ch0loop:
@ref100:
	.byte $80,$0e,$91,$0b,$01,$0a,$81
@ref101:
	.byte $0e,$91,$0b,$01,$0a,$81
	.byte $ff,$06
	.word @ref101
@ref103:
	.byte $0e,$85,$10,$85,$0e,$85,$0a,$85
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
	.byte $ff,$08
	.word @ref103
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
	.byte $ff,$08
	.word @ref103
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
	.byte $ff,$06
	.word @ref101
@ref115:
	.byte $0f,$00,$99
	.byte $fd
	.word @song1ch0loop

; E1M4: Kitchen Ace (And Taking Names)
@song1ch1:
@song1ch1loop:
@ref116:
	.byte $80,$1c,$91,$19,$01,$18,$81
@ref117:
	.byte $1c,$91,$19,$01,$18,$81
	.byte $ff,$06
	.word @ref117
@ref119:
	.byte $1c,$85,$1e,$85,$1c,$85,$18,$85
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
	.byte $ff,$08
	.word @ref119
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
	.byte $ff,$08
	.word @ref119
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
	.byte $ff,$06
	.word @ref117
@ref131:
	.byte $1d,$00,$99
	.byte $fd
	.word @song1ch1loop

; E1M4: Kitchen Ace (And Taking Names)
@song1ch2:
@song1ch2loop:
@ref132:
	.byte $86,$32,$8a,$26,$86,$32,$8a,$26,$8e,$42,$8a,$26,$83,$86,$32,$8a
	.byte $26,$86,$32,$8a,$22,$8e,$43,$8a,$22,$81
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
@ref135:
	.byte $86,$32,$8a,$26,$83,$8e,$42,$8a,$28,$83,$86,$32,$8a,$26,$83,$8e
	.byte $42,$8a,$22,$83
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0c
	.word @ref135
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0c
	.word @ref135
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
	.byte $ff,$0e
	.word @ref132
@ref147:
	.byte $8c,$48,$48,$48,$48,$40,$40,$40,$40,$34,$34,$34,$34,$2a,$2a,$2a
	.byte $2a
	.byte $fd
	.word @song1ch2loop

; E1M4: Kitchen Ace (And Taking Names)
@song1ch3:
	.byte $fb,$04
@song1ch3loop:
@ref148:
	.byte $fb,$04,$94,$10,$fb,$05,$85,$fb,$04,$0c,$fb,$05,$85,$fb,$04,$10
	.byte $fb,$05,$85,$fb,$04,$0c,$fb,$05,$85
@ref149:
	.byte $fb,$04,$10,$fb,$05,$85,$fb,$04,$0c,$fb,$05,$85,$fb,$04,$10,$fb
	.byte $05,$85,$fb,$04,$0c,$fb,$05,$85
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
	.byte $ff,$08
	.word @ref149
@ref163:
	.byte $fb,$04,$96,$0e,$fb,$05,$84,$0e,$0e,$0e,$fb,$04,$92,$12,$fb,$05
	.byte $85,$fb,$04,$12,$fb,$05,$85,$fb,$04,$12,$fb,$05,$85
	.byte $fd
	.word @song1ch3loop

; E1M4: Kitchen Ace (And Taking Names)
@song1ch4:
@song1ch4loop:
@ref164:
	.byte $9f
@ref165:
	.byte $9f
@ref166:
	.byte $9f
@ref167:
	.byte $9f
@ref168:
	.byte $9f
@ref169:
	.byte $9f
@ref170:
	.byte $9f
@ref171:
	.byte $9f
@ref172:
	.byte $9f
@ref173:
	.byte $9f
@ref174:
	.byte $9f
@ref175:
	.byte $9f
@ref176:
	.byte $9f
@ref177:
	.byte $9f
@ref178:
	.byte $9f
@ref179:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


; E1M3: Dark Halls
@song2ch0:
@ref180:
	.byte $8a,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09
	.byte $08,$81
@ref181:
	.byte $09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$09,$08
	.byte $81
	.byte $ff,$11
	.word @ref181
	.byte $ff,$11
	.word @ref181
@song2ch0loop:
@ref184:
	.byte $90,$38,$bd
@ref185:
	.byte $bf
@ref186:
	.byte $40,$bd
@ref187:
	.byte $32,$bd
@ref188:
	.byte $38,$bd
@ref189:
	.byte $bf
@ref190:
	.byte $40,$bd
@ref191:
	.byte $32,$bd
@ref192:
	.byte $2e,$bd
@ref193:
	.byte $bf
@ref194:
	.byte $3c,$bd
@ref195:
	.byte $28,$bd
@ref196:
	.byte $2e,$bd
@ref197:
	.byte $bf
@ref198:
	.byte $3c,$bd
@ref199:
	.byte $28,$bd
	.byte $fd
	.word @song2ch0loop

; E1M3: Dark Halls
@song2ch1:
@ref200:
	.byte $00,$bd
@ref201:
	.byte $bf
@ref202:
	.byte $00,$bd
@ref203:
	.byte $bf
@song2ch1loop:
@ref204:
	.byte $00,$bd
@ref205:
	.byte $90,$34,$bd
@ref206:
	.byte $bf
@ref207:
	.byte $3e,$bd
@ref208:
	.byte $00,$bd
@ref209:
	.byte $34,$bd
@ref210:
	.byte $bf
@ref211:
	.byte $3e,$bd
@ref212:
	.byte $00,$bd
@ref213:
	.byte $2a,$bd
@ref214:
	.byte $bf
@ref215:
	.byte $38,$bd
@ref216:
	.byte $00,$bd
@ref217:
	.byte $2a,$bd
@ref218:
	.byte $bf
@ref219:
	.byte $38,$bd
	.byte $fd
	.word @song2ch1loop

; E1M3: Dark Halls
@song2ch2:
@ref220:
	.byte $86,$32,$8a,$20,$98,$21,$21,$21,$21,$21,$86,$32,$8a,$20,$98,$21
	.byte $8c,$44,$8a,$20,$98,$21,$21,$21,$21,$21,$21,$20,$81
	.byte $ff,$14
	.word @ref220
	.byte $ff,$14
	.word @ref220
	.byte $ff,$14
	.word @ref220
@song2ch2loop:
	.byte $ff,$14
	.word @ref220
	.byte $ff,$14
	.word @ref220
	.byte $ff,$14
	.word @ref220
	.byte $ff,$14
	.word @ref220
@ref228:
	.byte $86,$32,$8a,$20,$98,$21,$21,$21,$21,$21,$86,$32,$8a,$20,$98,$21
	.byte $8c,$44,$8a,$20,$98,$21,$21,$21,$21,$21,$86,$32,$8a,$20,$98,$20
	.byte $81
@ref229:
	.byte $21,$21,$86,$32,$8a,$20,$98,$21,$21,$21,$86,$32,$8a,$20,$98,$21
	.byte $8c,$44,$8a,$20,$98,$21,$21,$21,$21,$21,$21,$20,$81
	.byte $ff,$15
	.word @ref228
	.byte $ff,$14
	.word @ref229
@ref232:
	.byte $86,$32,$8a,$2e,$2f,$2f,$2f,$2f,$2f,$86,$32,$8a,$2e,$2f,$8c,$44
	.byte $8a,$2e,$2f,$2f,$2f,$2f,$2f,$2f,$2e,$81
	.byte $ff,$14
	.word @ref232
@ref234:
	.byte $86,$32,$8a,$34,$35,$35,$35,$35,$35,$86,$32,$8a,$34,$35,$8c,$44
	.byte $8a,$34,$35,$35,$35,$35,$35,$35,$34,$81
@ref235:
	.byte $86,$32,$8a,$38,$39,$39,$39,$39,$39,$86,$32,$8a,$38,$39,$8c,$44
	.byte $8a,$38,$39,$39,$39,$39,$39,$39,$38,$81
	.byte $ff,$14
	.word @ref232
	.byte $ff,$14
	.word @ref232
	.byte $ff,$14
	.word @ref234
	.byte $ff,$14
	.word @ref235
	.byte $fd
	.word @song2ch2loop

; E1M3: Dark Halls
@song2ch3:
@ref240:
	.byte $92,$12,$95,$12,$85,$84,$0e,$9d
	.byte $ff,$06
	.word @ref240
	.byte $ff,$06
	.word @ref240
	.byte $ff,$06
	.word @ref240
@song2ch3loop:
	.byte $ff,$06
	.word @ref240
	.byte $ff,$06
	.word @ref240
	.byte $ff,$06
	.word @ref240
	.byte $ff,$06
	.word @ref240
@ref248:
	.byte $92,$12,$95,$12,$85,$84,$0e,$95,$92,$12,$85
@ref249:
	.byte $87,$12,$8d,$12,$85,$84,$0e,$9d
	.byte $ff,$08
	.word @ref248
	.byte $ff,$07
	.word @ref249
	.byte $ff,$08
	.word @ref248
	.byte $ff,$07
	.word @ref249
	.byte $ff,$08
	.word @ref248
	.byte $ff,$07
	.word @ref249
	.byte $ff,$08
	.word @ref248
	.byte $ff,$07
	.word @ref249
	.byte $ff,$08
	.word @ref248
	.byte $ff,$07
	.word @ref249
	.byte $fd
	.word @song2ch3loop

; E1M3: Dark Halls
@song2ch4:
	.byte $fb,$03
@ref260:
	.byte $fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb
	.byte $04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03
	.byte $81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81
	.byte $fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb
	.byte $04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03
	.byte $81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
@song2ch4loop:
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $ff,$20
	.word @ref260
	.byte $fd
	.word @song2ch4loop


; Flash Man
@song3ch0:
	.byte $fb,$05
@song3ch0loop:
@ref280:
	.byte $80,$22,$8d,$28,$85,$30,$85,$36,$89,$34,$89,$2c,$85
@ref281:
	.byte $32,$89,$30,$89,$28,$85,$2c,$85,$28,$85,$23,$1e,$85,$22,$81
@ref282:
	.byte $87,$3f,$3f,$3f,$40,$89,$3f,$3f,$3f,$40,$91
@ref283:
	.byte $87,$3f,$3f,$3f,$40,$85,$48,$85,$49,$44,$85,$40,$85,$3e,$85
@ref284:
	.byte $22,$8d,$28,$85,$30,$85,$36,$89,$34,$89,$2c,$85
	.byte $ff,$0f
	.word @ref281
	.byte $ff,$0b
	.word @ref282
	.byte $ff,$0f
	.word @ref283
	.byte $ff,$0c
	.word @ref284
	.byte $ff,$0f
	.word @ref281
@ref290:
	.byte $87,$49,$49,$49,$48,$89,$49,$49,$49,$48,$91
@ref291:
	.byte $87,$49,$49,$49,$48,$85,$52,$85,$53,$4e,$85,$48,$85,$48,$85
@ref292:
	.byte $3a,$8d,$40,$85,$48,$85,$4e,$89,$4c,$89,$44,$85
@ref293:
	.byte $4a,$89,$48,$89,$40,$85,$44,$85,$40,$85,$3b,$36,$85,$3a,$81
	.byte $ff,$0b
	.word @ref290
@ref295:
	.byte $45,$44,$85,$44,$85,$44,$85,$45,$48,$9d
@ref296:
	.byte $83,$3b,$49,$45,$48,$85,$45,$41,$45,$48,$85,$3a,$8d,$40,$81
@ref297:
	.byte $3e,$85,$3e,$85,$3f,$3b,$37,$3a,$95,$3b,$41,$44,$81
	.byte $ff,$0f
	.word @ref296
@ref299:
	.byte $3e,$85,$3e,$85,$3f,$3b,$37,$3a,$95,$3b,$41,$48,$81
@ref300:
	.byte $4e,$9d,$4c,$8d,$4a,$8d
@ref301:
	.byte $48,$bd
	.byte $ff,$06
	.word @ref300
@ref303:
	.byte $48,$bd
	.byte $fd
	.word @song3ch0loop

; Flash Man
@song3ch1:
@song3ch1loop:
@ref304:
	.byte $00,$85,$80,$22,$8d,$28,$85,$30,$85,$36,$89,$34,$89
@ref305:
	.byte $2c,$85,$32,$89,$30,$89,$28,$85,$2c,$85,$28,$85,$23,$1e,$81
@ref306:
	.byte $87,$57,$57,$57,$58,$89,$57,$57,$57,$58,$91
@ref307:
	.byte $87,$57,$57,$57,$58,$85,$60,$85,$61,$5c,$85,$58,$85,$56,$85
@ref308:
	.byte $00,$85,$22,$8d,$28,$85,$30,$85,$36,$89,$34,$89
	.byte $ff,$0f
	.word @ref305
	.byte $ff,$0b
	.word @ref306
	.byte $ff,$0f
	.word @ref307
	.byte $ff,$0c
	.word @ref308
	.byte $ff,$0f
	.word @ref305
@ref314:
	.byte $87,$3f,$3f,$3f,$41,$3e,$40,$3e,$40,$3f,$3f,$3f,$41,$3e,$40,$3e
	.byte $40,$3e,$40,$3e,$40
@ref315:
	.byte $3f,$41,$3f,$3f,$3f,$40,$85,$48,$85,$49,$44,$85,$40,$85,$3e,$85
@ref316:
	.byte $00,$85,$3a,$8d,$40,$85,$48,$85,$4e,$89,$4c,$89
@ref317:
	.byte $44,$85,$4a,$89,$48,$89,$40,$85,$44,$85,$40,$85,$3b,$36,$81
	.byte $ff,$15
	.word @ref314
@ref319:
	.byte $4f,$4e,$85,$4e,$85,$4e,$85,$4f,$52,$9d
@ref320:
	.byte $40,$45,$41,$40,$44,$40,$3e,$41,$3f,$3e,$40,$3e,$36,$3b,$3b,$36
	.byte $3b,$36,$3b,$3b,$36,$3a,$81
	.byte $ff,$17
	.word @ref320
	.byte $ff,$17
	.word @ref320
	.byte $ff,$17
	.word @ref320
@ref324:
	.byte $00,$bd
@ref325:
	.byte $29,$22,$85,$29,$23,$23,$28,$22,$2c,$28,$2e,$2c,$30,$2e,$2e,$30
	.byte $30,$2e,$2c,$30,$28,$2c,$22,$28,$1e,$22
@ref326:
	.byte $1e,$bd
@ref327:
	.byte $29,$22,$85,$29,$23,$23,$28,$22,$2c,$28,$3a,$2c,$30,$3a,$30,$30
	.byte $30,$30,$38,$30,$3e,$38,$44,$3e,$48,$44
	.byte $fd
	.word @song3ch1loop

; Flash Man
@song3ch2:
@song3ch2loop:
@ref328:
	.byte $bf
@ref329:
	.byte $bf
@ref330:
	.byte $80,$0a,$0a,$18,$0a,$18,$22,$0a,$0a,$24,$22,$0a,$22,$3a,$52,$3a
	.byte $06,$0a,$0a,$22,$0a,$22,$0a,$0a,$18,$0a,$22,$3a,$52,$3a,$22,$0a
	.byte $22
@ref331:
	.byte $0a,$0a,$18,$0a,$18,$22,$0a,$0a,$24,$22,$0a,$22,$3a,$52,$3a,$06
	.byte $18,$18,$30,$18,$2c,$14,$14,$22,$10,$28,$40,$58,$30,$18,$18,$18
@ref332:
	.byte $23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$23,$22
	.byte $81
	.byte $ff,$11
	.word @ref332
@ref334:
	.byte $0a,$0a,$18,$0a,$18,$22,$0a,$0a,$24,$22,$0a,$22,$3a,$52,$3a,$06
	.byte $0a,$0a,$22,$0a,$22,$0a,$0a,$18,$0a,$22,$3a,$52,$3a,$22,$0a,$22
	.byte $ff,$20
	.word @ref331
	.byte $ff,$11
	.word @ref332
	.byte $ff,$11
	.word @ref332
	.byte $ff,$20
	.word @ref334
	.byte $ff,$20
	.word @ref331
	.byte $ff,$11
	.word @ref332
	.byte $ff,$11
	.word @ref332
	.byte $ff,$20
	.word @ref334
@ref343:
	.byte $06,$06,$14,$06,$14,$1e,$06,$06,$22,$1e,$06,$1e,$36,$4e,$36,$02
	.byte $0a,$9d
@ref344:
	.byte $23,$22,$85,$23,$22,$29,$31,$28,$23,$23,$22,$85,$23,$22,$29,$31
	.byte $28,$22,$81
@ref345:
	.byte $1f,$1e,$85,$1f,$1e,$27,$2d,$26,$1f,$23,$22,$85,$23,$22,$29,$31
	.byte $28,$22,$81
	.byte $ff,$13
	.word @ref344
	.byte $ff,$13
	.word @ref345
@ref348:
	.byte $29,$29,$29,$29,$29,$29,$29,$29,$27,$27,$27,$27,$25,$25,$25,$24
	.byte $81
	.byte $ff,$20
	.word @ref334
	.byte $ff,$11
	.word @ref348
@ref351:
	.byte $0a,$0a,$18,$0a,$18,$22,$0a,$0a,$24,$22,$0a,$22,$3a,$52,$3a,$06
	.byte $0a,$0a,$22,$0a,$22,$0a,$0a,$18,$18,$30,$48,$60,$48,$30,$18,$30
	.byte $fd
	.word @song3ch2loop

; Flash Man
@song3ch3:
@song3ch3loop:
@ref352:
	.byte $bf
@ref353:
	.byte $bf
@ref354:
	.byte $84,$02,$bd
@ref355:
	.byte $bf
@ref356:
	.byte $bf
@ref357:
	.byte $bf
@ref358:
	.byte $02,$bd
@ref359:
	.byte $b3,$8a,$1d,$86,$11,$88,$1a,$1c
@ref360:
	.byte $1a,$8a,$1c,$88,$1a,$8a,$1c,$86,$11,$88,$1a,$8a,$1d,$88,$1a,$8a
	.byte $1d,$86,$11,$88,$1a,$1c,$1a,$8a,$1c,$88,$1a,$8a,$1c,$86,$11,$88
	.byte $1a,$8a,$1d,$88,$1a,$8a,$1d,$86,$11,$88,$1a,$1c
	.byte $ff,$18
	.word @ref360
@ref362:
	.byte $84,$02,$85,$86,$11,$88,$1a,$8a,$1d,$88,$1a,$8a,$1d,$86,$11,$88
	.byte $1a,$1c,$1a,$8a,$1c,$88,$1a,$8a,$1c,$86,$11,$88,$1a,$8a,$1d,$88
	.byte $1a,$8a,$1d,$86,$11,$88,$1a,$1c
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$16
	.word @ref362
@ref367:
	.byte $86,$11,$11,$88,$1b,$86,$11,$88,$1b,$86,$11,$88,$1b,$86,$11,$10
	.byte $99,$10,$10
@ref368:
	.byte $88,$1a,$8a,$1c,$88,$1a,$8a,$1c,$86,$11,$88,$1a,$8a,$1d,$88,$1a
	.byte $8a,$1d,$86,$11,$88,$1a,$1c,$1a,$8a,$1c,$88,$1a,$8a,$1c,$86,$11
	.byte $88,$1a,$8a,$1d,$88,$1a,$8a,$1d,$86,$11,$88,$1a,$1c
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $ff,$18
	.word @ref360
	.byte $fd
	.word @song3ch3loop

; Flash Man
@song3ch4:
@song3ch4loop:
@ref376:
	.byte $bf
@ref377:
	.byte $bf
@ref378:
	.byte $bf
@ref379:
	.byte $bf
@ref380:
	.byte $bf
@ref381:
	.byte $bf
@ref382:
	.byte $bf
@ref383:
	.byte $b3,$33,$34,$85
@ref384:
	.byte $32,$85,$34,$89,$33,$34,$85,$32,$85,$35,$32,$85,$33,$35,$32,$81
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
@ref391:
	.byte $35,$35,$33,$35,$33,$35,$33,$35,$34,$85,$32,$85,$32,$85,$33,$34
	.byte $34
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $ff,$10
	.word @ref384
	.byte $fd
	.word @song3ch4loop


; Metal Man
@song4ch0:
	.byte $fb,$03
@song4ch0loop:
@ref400:
	.byte $bf
@ref401:
	.byte $bf
@ref402:
	.byte $80,$1a,$1c,$ab,$1a,$1c,$8b
@ref403:
	.byte $1a,$1c,$8b,$1a,$1c,$8b,$1a,$1c,$9b
@ref404:
	.byte $bf
@ref405:
	.byte $bf
@ref406:
	.byte $20,$24,$ab,$20,$24,$8b
@ref407:
	.byte $20,$24,$8b,$20,$24,$8b,$20,$24,$9b
@ref408:
	.byte $2e,$a9,$01,$2f,$3d,$2f,$38,$81
@ref409:
	.byte $3d,$34,$87,$38,$39,$35,$34,$38,$2e,$8d,$35,$2a,$2e,$2a,$83,$2a
	.byte $2e,$81
@ref410:
	.byte $97,$32,$83,$2e,$34,$85,$33,$2e,$8d,$34,$81
@ref411:
	.byte $4c,$89,$01,$50,$89,$01,$4d,$01,$4d,$01,$50,$89,$00,$81
	.byte $ff,$08
	.word @ref408
	.byte $ff,$12
	.word @ref409
	.byte $ff,$0b
	.word @ref410
	.byte $ff,$0e
	.word @ref411
@ref416:
	.byte $47,$47,$43,$01,$47,$01,$43,$01,$46,$89,$01,$3d,$01,$42,$85
@ref417:
	.byte $00,$85,$46,$a1,$01,$47,$54,$89
@ref418:
	.byte $69,$5e,$68,$56,$5e,$50,$56,$68,$50,$5e,$68,$56,$5e,$50,$56,$62
	.byte $50,$5a,$62,$50,$5a,$4a,$50,$62,$4a,$5a,$62,$50,$5a,$4a,$50
@ref419:
	.byte $5e,$4a,$54,$5e,$4c,$54,$46,$4c,$5e,$46,$54,$5e,$4c,$54,$46,$4c
	.byte $5e,$46,$54,$5e,$4c,$54,$46,$4c,$5c,$46,$54,$5c,$50,$54,$4a,$50
	.byte $ff,$0f
	.word @ref416
	.byte $ff,$08
	.word @ref417
	.byte $ff,$1f
	.word @ref418
@ref423:
	.byte $83,$25,$2b,$2f,$35,$39,$3d,$46,$3c,$34,$2e,$46,$3c,$34,$2e,$46
	.byte $3c,$34,$2e,$46,$3c,$34,$2e,$46,$3c
@ref424:
	.byte $50,$8b,$00,$4c,$8b,$00,$4a,$8b,$00,$4d,$50,$89
@ref425:
	.byte $47,$01,$47,$01,$47,$42,$87,$00,$46,$8b,$00,$47,$54,$87,$00
@ref426:
	.byte $50,$8b,$00,$4c,$8b,$00,$4a,$8b,$00,$4d,$50,$85,$54,$81
@ref427:
	.byte $01,$54,$85,$01,$55,$51,$4d,$51,$4d,$4b,$4d,$4b,$47,$4b,$47,$42
	.byte $81
	.byte $ff,$0c
	.word @ref424
	.byte $ff,$0f
	.word @ref425
	.byte $ff,$0e
	.word @ref426
@ref431:
	.byte $01,$55,$55,$01,$55,$01,$55,$01,$54,$89,$33,$33,$3c,$89
@ref432:
	.byte $bf
@ref433:
	.byte $bf
@ref434:
	.byte $bf
@ref435:
	.byte $bf
@ref436:
	.byte $bf
@ref437:
	.byte $bf
@ref438:
	.byte $16,$9d,$24,$9d
@ref439:
	.byte $32,$ad,$38,$8d
@ref440:
	.byte $36,$9d,$3c,$9d
@ref441:
	.byte $32,$ad,$34,$8d
@ref442:
	.byte $38,$a5,$34,$89,$32,$89
@ref443:
	.byte $2e,$ad,$32,$8d
@ref444:
	.byte $33,$33,$2f,$01,$33,$01,$2f,$01,$32,$9d
@ref445:
	.byte $46,$89,$01,$4a,$89,$01,$47,$01,$47,$01,$4a,$89,$00,$81
@ref446:
	.byte $34,$9d,$38,$9d
@ref447:
	.byte $3c,$9d,$3e,$9d
@ref448:
	.byte $3c,$ad,$2f,$3d,$2f,$38,$81
@ref449:
	.byte $3d,$34,$87,$38,$39,$35,$34,$38,$2e,$a1
@ref450:
	.byte $34,$9d,$38,$85,$34,$85,$32,$85,$2e,$85
@ref451:
	.byte $2a,$9d,$32,$9d
	.byte $fd
	.word @song4ch0loop

; Metal Man
@song4ch1:
@song4ch1loop:
@ref452:
	.byte $96,$47,$4d,$54,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$46
	.byte $81
@ref453:
	.byte $83,$4d,$54,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$46,$81
@ref454:
	.byte $47,$4d,$54,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$46,$81
	.byte $ff,$10
	.word @ref453
	.byte $ff,$10
	.word @ref454
	.byte $ff,$10
	.word @ref453
	.byte $ff,$10
	.word @ref454
	.byte $ff,$10
	.word @ref453
	.byte $ff,$10
	.word @ref454
	.byte $ff,$10
	.word @ref453
@ref462:
	.byte $83,$4d,$54,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$80,$46
	.byte $81
@ref463:
	.byte $8b,$01,$32,$89,$01,$2f,$01,$2f,$01,$32,$89,$00,$81
	.byte $ff,$10
	.word @ref452
	.byte $ff,$10
	.word @ref453
	.byte $ff,$10
	.word @ref462
	.byte $ff,$0d
	.word @ref463
@ref468:
	.byte $96,$47,$47,$46,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$80
	.byte $46,$81
@ref469:
	.byte $83,$96,$47,$46,$85,$46,$89,$47,$4b,$4d,$4b,$46,$85,$47,$43,$46
	.byte $81
@ref470:
	.byte $80,$50,$93,$00,$4c,$83,$00,$4a,$87,$00,$4c,$87,$00,$4a,$83,$00
@ref471:
	.byte $46,$a5,$3c,$83,$00,$42,$83,$00,$44,$85
	.byte $ff,$10
	.word @ref468
	.byte $ff,$10
	.word @ref469
	.byte $ff,$0f
	.word @ref470
@ref475:
	.byte $4c,$83,$00,$4c,$83,$00,$4a,$89,$4c,$85,$00,$89,$47,$54,$89
@ref476:
	.byte $87,$50,$8b,$00,$4c,$8b,$00,$4a,$8b,$00,$4d,$50,$81
@ref477:
	.byte $4d,$01,$4d,$01,$4d,$4a,$87,$00,$4c,$8b,$00,$87,$47,$54,$81
	.byte $ff,$0d
	.word @ref476
@ref479:
	.byte $83,$55,$01,$54,$87,$55,$51,$4d,$51,$4d,$4b,$4d,$4b,$47,$4b,$46
	.byte $ff,$0d
	.word @ref476
	.byte $ff,$0f
	.word @ref477
@ref482:
	.byte $87,$50,$8b,$00,$4c,$8b,$00,$4a,$8b,$00,$4d,$4a,$81
@ref483:
	.byte $01,$4b,$4b,$01,$4b,$01,$4b,$01,$4a,$89,$3d,$3d,$42,$89
	.byte $ff,$10
	.word @ref452
	.byte $ff,$10
	.word @ref453
@ref486:
	.byte $43,$4b,$50,$85,$42,$89,$43,$47,$4b,$47,$42,$85,$43,$41,$42,$81
@ref487:
	.byte $83,$49,$50,$85,$42,$89,$43,$47,$49,$47,$42,$85,$43,$3f,$42,$81
@ref488:
	.byte $41,$47,$4e,$85,$40,$89,$41,$45,$47,$45,$40,$85,$41,$3d,$40,$81
@ref489:
	.byte $83,$45,$4c,$85,$3e,$89,$3f,$43,$45,$43,$3e,$85,$3f,$3b,$3e,$81
@ref490:
	.byte $3d,$43,$4a,$85,$3c,$89,$3d,$41,$43,$41,$3c,$85,$3d,$39,$3c,$81
@ref491:
	.byte $83,$43,$4a,$85,$3c,$89,$3d,$41,$43,$41,$3c,$85,$3d,$39,$3c,$81
	.byte $ff,$10
	.word @ref490
	.byte $ff,$10
	.word @ref491
@ref494:
	.byte $39,$3f,$46,$85,$38,$89,$39,$3d,$3f,$3d,$38,$85,$39,$35,$38,$81
@ref495:
	.byte $83,$3f,$46,$85,$38,$89,$39,$3d,$3f,$3d,$38,$85,$39,$35,$38,$81
	.byte $ff,$10
	.word @ref490
@ref497:
	.byte $80,$40,$89,$01,$42,$89,$01,$41,$01,$41,$01,$42,$89,$00,$81
@ref498:
	.byte $96,$3f,$47,$4c,$85,$3e,$89,$3f,$43,$47,$43,$3e,$85,$3f,$3d,$3e
	.byte $81
@ref499:
	.byte $3f,$47,$4c,$85,$3e,$89,$3f,$43,$47,$43,$3e,$85,$3f,$3d,$3e,$81
	.byte $ff,$10
	.word @ref454
	.byte $ff,$10
	.word @ref453
	.byte $ff,$10
	.word @ref499
	.byte $ff,$10
	.word @ref486
	.byte $fd
	.word @song4ch1loop

; Metal Man
@song4ch2:
@song4ch2loop:
@ref504:
	.byte $bf
@ref505:
	.byte $bf
@ref506:
	.byte $bf
@ref507:
	.byte $bf
@ref508:
	.byte $bf
@ref509:
	.byte $bf
@ref510:
	.byte $80,$2f,$01,$2f,$01,$16,$9d,$00,$8d
@ref511:
	.byte $9f,$2f,$01,$2f,$01,$2b,$01,$2b,$00,$81
@ref512:
	.byte $2f,$01,$2f,$01,$2a,$89,$01,$2e,$85,$01,$2f,$34,$85,$3c,$85
@ref513:
	.byte $2f,$01,$2f,$01,$2a,$89,$01,$2e,$85,$01,$2f,$2e,$83,$00,$2a,$83
	.byte $00
@ref514:
	.byte $27,$01,$27,$01,$24,$89,$01,$26,$85,$01,$27,$26,$83,$00,$24,$83
	.byte $00
@ref515:
	.byte $26,$8b,$00,$2a,$8b,$00,$27,$01,$26,$85,$2a,$8d
	.byte $ff,$0f
	.word @ref512
@ref517:
	.byte $2f,$01,$2f,$01,$2a,$85,$01,$01,$2e,$85,$01,$2f,$2e,$83,$00,$2a
	.byte $83,$00
	.byte $ff,$11
	.word @ref514
	.byte $ff,$0c
	.word @ref515
@ref520:
	.byte $2f,$01,$2f,$01,$2a,$8b,$00,$2e,$85,$01,$2f,$34,$85,$3c,$85
@ref521:
	.byte $39,$01,$39,$01,$34,$8b,$00,$38,$87,$00,$39,$2e,$85,$2a,$85
@ref522:
	.byte $26,$8d,$00,$85,$27,$01,$2a,$85,$01,$2b,$2b,$01,$2b,$00,$81
@ref523:
	.byte $2e,$8b,$00,$2a,$85,$01,$2f,$01,$2e,$85,$01,$2b,$01,$2d,$00,$81
	.byte $ff,$0f
	.word @ref520
	.byte $ff,$0f
	.word @ref521
	.byte $ff,$0f
	.word @ref522
@ref527:
	.byte $8d,$00,$2a,$85,$01,$2f,$00,$9d
@ref528:
	.byte $21,$21,$1d,$01,$21,$01,$1d,$20,$83,$00,$21,$20,$83,$00,$20,$83
	.byte $00,$1d,$1a,$81
@ref529:
	.byte $1d,$01,$1d,$01,$1d,$1a,$83,$00,$1b,$1c,$85,$01,$1d,$20,$83,$00
	.byte $24,$83,$00
@ref530:
	.byte $21,$21,$1d,$01,$21,$01,$1d,$20,$83,$00,$21,$20,$83,$00,$20,$83
	.byte $00,$1d,$20,$81
@ref531:
	.byte $25,$01,$25,$01,$25,$20,$83,$00,$21,$24,$85,$01,$25,$24,$83,$00
	.byte $24,$83,$00
	.byte $ff,$14
	.word @ref528
	.byte $ff,$13
	.word @ref529
	.byte $ff,$14
	.word @ref530
	.byte $ff,$13
	.word @ref531
@ref536:
	.byte $bf
@ref537:
	.byte $bf
@ref538:
	.byte $bf
@ref539:
	.byte $bf
@ref540:
	.byte $bf
@ref541:
	.byte $bf
@ref542:
	.byte $25,$01,$25,$01,$20,$89,$01,$24,$85,$01,$25,$2a,$85,$32,$85
@ref543:
	.byte $25,$01,$25,$01,$20,$89,$01,$24,$85,$01,$25,$24,$83,$00,$20,$83
	.byte $00
	.byte $ff,$0f
	.word @ref542
	.byte $ff,$11
	.word @ref543
@ref546:
	.byte $21,$01,$21,$01,$1c,$89,$01,$20,$85,$01,$21,$26,$85,$2e,$85
@ref547:
	.byte $21,$01,$21,$01,$1c,$89,$01,$20,$85,$01,$21,$20,$83,$00,$1c,$83
	.byte $00
	.byte $ff,$0f
	.word @ref542
	.byte $ff,$11
	.word @ref543
@ref550:
	.byte $27,$01,$27,$01,$24,$89,$01,$26,$85,$01,$27,$2e,$85,$34,$85
	.byte $ff,$0f
	.word @ref550
	.byte $ff,$0f
	.word @ref512
	.byte $ff,$12
	.word @ref517
	.byte $ff,$0f
	.word @ref550
@ref555:
	.byte $2b,$01,$2b,$01,$28,$89,$01,$2a,$85,$01,$2b,$32,$85,$38,$85
	.byte $fd
	.word @song4ch2loop

; Metal Man
@song4ch3:
@song4ch3loop:
@ref556:
	.byte $bf
@ref557:
	.byte $bf
@ref558:
	.byte $bf
@ref559:
	.byte $bf
@ref560:
	.byte $bf
@ref561:
	.byte $bf
@ref562:
	.byte $88,$18,$85,$18,$85,$86,$10,$ad
@ref563:
	.byte $9f,$88,$19,$19,$18,$85,$86,$10,$85,$88,$19,$18,$81
@ref564:
	.byte $18,$85,$18,$85,$86,$10,$85,$88,$19,$19,$19,$19,$18,$85,$86,$10
	.byte $85,$88,$19,$18,$81
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
@ref579:
	.byte $18,$85,$18,$85,$86,$10,$85,$88,$19,$19,$18,$9d
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
@ref583:
	.byte $8a,$0c,$85,$88,$19,$19,$8a,$0c,$85,$88,$19,$19,$8a,$0c,$85,$88
	.byte $19,$19,$8a,$0c,$85,$88,$19,$18,$81
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref564
	.byte $ff,$11
	.word @ref583
@ref588:
	.byte $bf
@ref589:
	.byte $bf
@ref590:
	.byte $bf
@ref591:
	.byte $bf
@ref592:
	.byte $bf
@ref593:
	.byte $bf
@ref594:
	.byte $8a,$18,$8d,$18,$8d,$86,$10,$8d,$8a,$18,$8d
@ref595:
	.byte $18,$8d,$18,$8d,$86,$10,$8d,$8a,$18,$8d
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $ff,$08
	.word @ref595
	.byte $fd
	.word @song4ch3loop

; Metal Man
@song4ch4:
@song4ch4loop:
@ref608:
	.byte $bf
@ref609:
	.byte $bf
@ref610:
	.byte $bf
@ref611:
	.byte $bf
@ref612:
	.byte $bf
@ref613:
	.byte $bf
@ref614:
	.byte $32,$8d,$34,$ad
@ref615:
	.byte $a3,$33,$32,$85,$34,$85,$32,$85
@ref616:
	.byte $32,$8d,$34,$95,$32,$85,$35,$32,$85,$32,$81
@ref617:
	.byte $87,$32,$85,$34,$85,$32,$89,$33,$32,$85,$34,$85,$32,$85
@ref618:
	.byte $32,$8d,$34,$95,$32,$85,$34,$85,$32,$85
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0b
	.word @ref616
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
@ref631:
	.byte $87,$32,$85,$34,$85,$32,$89,$39,$39,$39,$3b,$3b,$3d,$3c,$81
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
@ref635:
	.byte $32,$8d,$39,$39,$39,$39,$3b,$3b,$3b,$3b,$3d,$3d,$3d,$3c,$81
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0e
	.word @ref617
	.byte $ff,$0a
	.word @ref618
	.byte $ff,$0f
	.word @ref635
@ref640:
	.byte $bf
@ref641:
	.byte $bf
@ref642:
	.byte $bf
@ref643:
	.byte $bf
@ref644:
	.byte $bf
@ref645:
	.byte $bf
@ref646:
	.byte $32,$9d,$34,$9d
@ref647:
	.byte $8f,$32,$8d,$34,$8d,$32,$8d
@ref648:
	.byte $8f,$32,$8d,$34,$9d
@ref649:
	.byte $32,$95,$32,$85,$34,$8d,$32,$89,$32,$81
@ref650:
	.byte $32,$9d,$34,$9d
@ref651:
	.byte $8f,$32,$8d,$34,$8d,$32,$89,$32,$81
@ref652:
	.byte $97,$32,$85,$34,$9d
@ref653:
	.byte $32,$8d,$32,$8d,$34,$8d,$32,$8d
@ref654:
	.byte $32,$95,$32,$85,$34,$95,$32,$85
@ref655:
	.byte $87,$32,$8d,$32,$85,$34,$8d,$32,$89,$32,$81
@ref656:
	.byte $32,$9d,$34,$9d
	.byte $ff,$09
	.word @ref651
@ref658:
	.byte $32,$9d,$34,$9d
	.byte $ff,$09
	.word @ref651
	.byte $fd
	.word @song4ch4loop
