;
; File generated by cc65 v 2.19 - Git e95db437a
;
	.fopt		compiler,"cc65 v 2.19 - Git e95db437a"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_FamiToneInit
	.import		_FamiToneSfxInit
	.import		_FamiToneMusicPlay
	.import		_FamiToneSfxPlay
	.import		_FamiToneUpdate
	.importzp	_InputPort1
	.importzp	_InputPort1Prev
	.import		_WaitFrame
	.import		_WaitVBlank
	.import		_UnRLE
	.export		_BG_TITLE
	.export		_PAL_TITLE
	.export		_BG_SCREEN_TIMELINE
	.export		_PAL_SCREEN_TIMELINE
	.export		_BG_SCREEN_OTHEREXP
	.export		_PAL_SCREEN_OTHEREXP
	.export		_BG_SCREEN_CEH
	.export		_PAL_SCREEN_CEH
	.export		_BG_SCREEN_OSCP
	.export		_PAL_SCREEN_OSCP
	.export		_BG_SCREEN_CCSSA
	.export		_PAL_SCREEN_CCSSA
	.export		_BG_SCREEN_ONION
	.export		_PAL_SCREEN_ONION
	.export		_BG_SCREEN_SPEAKING
	.export		_PAL_SCREEN_SPEAKING
	.export		_BG_SCREEN_SPEAKING_2
	.export		_PAL_SCREEN_SPEAKING_2
	.export		_BG_SCREEN_NESDEV
	.export		_PAL_SCREEN_NESDEV
	.export		_BG_SCREEN_QR
	.export		_PAL_SCREEN_QR
	.export		_BG_SCREEN_END
	.export		_PAL_SCREEN_END
	.export		_i
	.export		_j
	.export		_state
	.export		_bg
	.export		_pattern_table
	.export		_ppu_addr
	.export		_ppu_data
	.export		_ppu_data_size
	.export		_text_sprites
	.export		_ResetScroll
	.export		_EnablePPU
	.export		_DisablePPU
	.export		_WritePPU
	.export		_DrawBackground
	.export		_InitTitle
	.export		_InitScreenTimeline
	.export		_InitScreenOTHEREXP
	.export		_InitScreenCEH
	.export		_InitScreenOSCP
	.export		_InitScreenCCSSA
	.export		_InitScreenONION
	.export		_InitScreenQR
	.export		_InitScreenSPEAKING
	.export		_InitScreenSPEAKING_2
	.export		_InitScreenNESDEV
	.export		_InitScreenEnd
	.export		_HandleInput
	.export		_Update
	.export		_main

.segment	"RODATA"

_BG_TITLE:
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$6B
	.byte	$35
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$3B
	.byte	$3C
	.byte	$3D
	.byte	$00
	.byte	$02
	.byte	$15
	.byte	$34
	.byte	$35
	.byte	$36
	.byte	$37
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$3B
	.byte	$3C
	.byte	$3D
	.byte	$00
	.byte	$02
	.byte	$15
	.byte	$44
	.byte	$45
	.byte	$46
	.byte	$47
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$4C
	.byte	$4D
	.byte	$00
	.byte	$02
	.byte	$15
	.byte	$54
	.byte	$55
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$59
	.byte	$5A
	.byte	$5B
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$3D
	.byte	$00
	.byte	$02
	.byte	$0F
	.byte	$64
	.byte	$65
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6C
	.byte	$00
	.byte	$02
	.byte	$16
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$7E
	.byte	$7F
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$11
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$8E
	.byte	$8F
	.byte	$7F
	.byte	$6F
	.byte	$6C
	.byte	$6D
	.byte	$6E
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$82
	.byte	$93
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$9F
	.byte	$8F
	.byte	$7F
	.byte	$00
	.byte	$7D
	.byte	$7E
	.byte	$7F
	.byte	$00
	.byte	$02
	.byte	$0D
	.byte	$A4
	.byte	$A5
	.byte	$A6
	.byte	$A7
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$AE
	.byte	$AF
	.byte	$9F
	.byte	$8F
	.byte	$00
	.byte	$8D
	.byte	$8E
	.byte	$8F
	.byte	$00
	.byte	$02
	.byte	$0D
	.byte	$B4
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$BE
	.byte	$BF
	.byte	$AF
	.byte	$9F
	.byte	$00
	.byte	$00
	.byte	$9E
	.byte	$9F
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$C3
	.byte	$C4
	.byte	$C5
	.byte	$C6
	.byte	$C7
	.byte	$C8
	.byte	$C9
	.byte	$CA
	.byte	$CB
	.byte	$CC
	.byte	$CD
	.byte	$CE
	.byte	$CF
	.byte	$BF
	.byte	$AF
	.byte	$00
	.byte	$00
	.byte	$AE
	.byte	$AF
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$D3
	.byte	$D4
	.byte	$D5
	.byte	$D6
	.byte	$D7
	.byte	$D8
	.byte	$D9
	.byte	$DA
	.byte	$DB
	.byte	$DC
	.byte	$DD
	.byte	$DE
	.byte	$DF
	.byte	$CF
	.byte	$BF
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$BF
	.byte	$00
	.byte	$02
	.byte	$0A
	.byte	$D2
	.byte	$D2
	.byte	$E3
	.byte	$E4
	.byte	$E5
	.byte	$E6
	.byte	$E7
	.byte	$E8
	.byte	$E9
	.byte	$EA
	.byte	$EB
	.byte	$EC
	.byte	$ED
	.byte	$EE
	.byte	$EF
	.byte	$DF
	.byte	$CF
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$CF
	.byte	$00
	.byte	$02
	.byte	$0A
	.byte	$E2
	.byte	$E2
	.byte	$F3
	.byte	$F4
	.byte	$F5
	.byte	$F6
	.byte	$F7
	.byte	$F8
	.byte	$F9
	.byte	$FA
	.byte	$FB
	.byte	$FC
	.byte	$FD
	.byte	$FE
	.byte	$FF
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$DF
	.byte	$00
	.byte	$02
	.byte	$0A
	.byte	$F2
	.byte	$F2
	.byte	$00
	.byte	$02
	.byte	$1F
	.byte	$30
	.byte	$02
	.byte	$0C
	.byte	$00
	.byte	$00
	.byte	$FC
	.byte	$FD
	.byte	$00
	.byte	$02
	.byte	$2E
	.byte	$12
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$17
	.byte	$25
	.byte	$00
	.byte	$13
	.byte	$14
	.byte	$0F
	.byte	$0E
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$02
	.byte	$30
	.byte	$0E
	.byte	$05
	.byte	$13
	.byte	$32
	.byte	$15
	.byte	$0D
	.byte	$05
	.byte	$00
	.byte	$0F
	.byte	$03
	.byte	$14
	.byte	$00
	.byte	$1D
	.byte	$1B
	.byte	$1D
	.byte	$1D
	.byte	$00
	.byte	$02
	.byte	$31
	.byte	$30
	.byte	$02
	.byte	$0C
	.byte	$00
	.byte	$02
	.byte	$53
	.byte	$10
	.byte	$12
	.byte	$05
	.byte	$13
	.byte	$13
	.byte	$00
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$12
	.byte	$14
	.byte	$00
	.byte	$02
	.byte	$73
	.byte	$A2
	.byte	$00
	.byte	$50
	.byte	$50
	.byte	$00
	.byte	$02
	.byte	$0F
	.byte	$05
	.byte	$05
	.byte	$02
	.byte	$00
_PAL_TITLE:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$31
	.byte	$0F
	.byte	$15
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_TIMELINE:
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$68
	.byte	$17
	.byte	$0F
	.byte	$12
	.byte	$0B
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$09
	.byte	$0D
	.byte	$05
	.byte	$0C
	.byte	$09
	.byte	$0E
	.byte	$05
	.byte	$00
	.byte	$07
	.byte	$69
	.byte	$04
	.byte	$05
	.byte	$0C
	.byte	$0F
	.byte	$09
	.byte	$14
	.byte	$14
	.byte	$05
	.byte	$00
	.byte	$46
	.byte	$47
	.byte	$00
	.byte	$07
	.byte	$08
	.byte	$40
	.byte	$41
	.byte	$42
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$13
	.byte	$01
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$1D
	.byte	$1B
	.byte	$1C
	.byte	$1C
	.byte	$3F
	.byte	$00
	.byte	$00
	.byte	$56
	.byte	$57
	.byte	$58
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$50
	.byte	$51
	.byte	$52
	.byte	$00
	.byte	$1D
	.byte	$1B
	.byte	$1D
	.byte	$1B
	.byte	$3F
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$1D
	.byte	$1B
	.byte	$1C
	.byte	$1F
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$66
	.byte	$67
	.byte	$68
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$60
	.byte	$61
	.byte	$62
	.byte	$00
	.byte	$14
	.byte	$0F
	.byte	$04
	.byte	$01
	.byte	$19
	.byte	$00
	.byte	$07
	.byte	$2C
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$08
	.byte	$33
	.byte	$07
	.byte	$03
	.byte	$6C
	.byte	$33
	.byte	$07
	.byte	$05
	.byte	$6C
	.byte	$33
	.byte	$07
	.byte	$04
	.byte	$6C
	.byte	$33
	.byte	$07
	.byte	$03
	.byte	$6C
	.byte	$33
	.byte	$07
	.byte	$03
	.byte	$3F
	.byte	$07
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$11
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$11
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$35
	.byte	$00
	.byte	$07
	.byte	$2E
	.byte	$16
	.byte	$01
	.byte	$12
	.byte	$09
	.byte	$0F
	.byte	$15
	.byte	$13
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$43
	.byte	$44
	.byte	$45
	.byte	$00
	.byte	$13
	.byte	$08
	.byte	$01
	.byte	$10
	.byte	$05
	.byte	$13
	.byte	$08
	.byte	$09
	.byte	$06
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$1D
	.byte	$1B
	.byte	$1B
	.byte	$1D
	.byte	$3F
	.byte	$00
	.byte	$07
	.byte	$08
	.byte	$53
	.byte	$54
	.byte	$55
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$1D
	.byte	$1B
	.byte	$1C
	.byte	$23
	.byte	$3F
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$1D
	.byte	$1B
	.byte	$1C
	.byte	$1C
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$63
	.byte	$64
	.byte	$65
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$1D
	.byte	$1B
	.byte	$1D
	.byte	$1B
	.byte	$00
	.byte	$07
	.byte	$FE
	.byte	$00
	.byte	$07
	.byte	$17
	.byte	$80
	.byte	$23
	.byte	$00
	.byte	$80
	.byte	$00
	.byte	$00
	.byte	$AA
	.byte	$07
	.byte	$06
	.byte	$20
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$0A
	.byte	$00
	.byte	$07
	.byte	$19
	.byte	$00
	.byte	$07
	.byte	$00
_PAL_SCREEN_TIMELINE:
	.byte	$0F
	.byte	$13
	.byte	$26
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$30
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_OTHEREXP:
	.byte	$0A
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$0F
	.byte	$14
	.byte	$08
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$05
	.byte	$18
	.byte	$10
	.byte	$05
	.byte	$12
	.byte	$09
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$08
	.byte	$0F
	.byte	$13
	.byte	$14
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$25
	.byte	$03
	.byte	$0F
	.byte	$0D
	.byte	$00
	.byte	$0A
	.byte	$0B
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$17
	.byte	$05
	.byte	$02
	.byte	$00
	.byte	$08
	.byte	$0F
	.byte	$13
	.byte	$14
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$01
	.byte	$0E
	.byte	$04
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$04
	.byte	$01
	.byte	$14
	.byte	$01
	.byte	$00
	.byte	$03
	.byte	$05
	.byte	$0E
	.byte	$14
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$04
	.byte	$0D
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$13
	.byte	$0F
	.byte	$03
	.byte	$0B
	.byte	$05
	.byte	$14
	.byte	$0C
	.byte	$01
	.byte	$02
	.byte	$13
	.byte	$00
	.byte	$0A
	.byte	$0C
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$05
	.byte	$0D
	.byte	$01
	.byte	$09
	.byte	$0C
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$12
	.byte	$16
	.byte	$09
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$0A
	.byte	$07
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$10
	.byte	$12
	.byte	$0F
	.byte	$16
	.byte	$09
	.byte	$04
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$0A
	.byte	$0C
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$18
	.byte	$06
	.byte	$09
	.byte	$0E
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$28
	.byte	$03
	.byte	$0F
	.byte	$0D
	.byte	$03
	.byte	$01
	.byte	$13
	.byte	$14
	.byte	$00
	.byte	$0A
	.byte	$07
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$08
	.byte	$09
	.byte	$07
	.byte	$08
	.byte	$00
	.byte	$06
	.byte	$12
	.byte	$05
	.byte	$11
	.byte	$15
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$19
	.byte	$00
	.byte	$03
	.byte	$01
	.byte	$02
	.byte	$0C
	.byte	$05
	.byte	$00
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$13
	.byte	$19
	.byte	$13
	.byte	$14
	.byte	$05
	.byte	$0D
	.byte	$00
	.byte	$05
	.byte	$0E
	.byte	$07
	.byte	$09
	.byte	$0E
	.byte	$05
	.byte	$05
	.byte	$12
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0D
	.byte	$02
	.byte	$0E
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$0D
	.byte	$05
	.byte	$12
	.byte	$09
	.byte	$03
	.byte	$01
	.byte	$00
	.byte	$0A
	.byte	$0A
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$02
	.byte	$01
	.byte	$0E
	.byte	$0B
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$29
	.byte	$00
	.byte	$06
	.byte	$09
	.byte	$0E
	.byte	$01
	.byte	$0E
	.byte	$03
	.byte	$09
	.byte	$01
	.byte	$0C
	.byte	$00
	.byte	$00
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$01
	.byte	$15
	.byte	$14
	.byte	$0F
	.byte	$0D
	.byte	$01
	.byte	$14
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$0A
	.byte	$0A
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$F8
	.byte	$F9
	.byte	$F8
	.byte	$F9
	.byte	$FA
	.byte	$FB
	.byte	$FA
	.byte	$FB
	.byte	$00
	.byte	$0A
	.byte	$17
	.byte	$FA
	.byte	$FB
	.byte	$FA
	.byte	$FB
	.byte	$00
	.byte	$0A
	.byte	$1F
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$F6
	.byte	$F6
	.byte	$F7
	.byte	$F7
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$0A
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$0A
	.byte	$21
	.byte	$AA
	.byte	$00
	.byte	$00
	.byte	$A0
	.byte	$0A
	.byte	$02
	.byte	$20
	.byte	$AA
	.byte	$AA
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$08
	.byte	$08
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$AA
	.byte	$AA
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$AA
	.byte	$00
	.byte	$0A
	.byte	$0E
	.byte	$00
	.byte	$0A
	.byte	$00
_PAL_SCREEN_OTHEREXP:
	.byte	$0F
	.byte	$13
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_CEH:
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$2D
	.byte	$35
	.byte	$00
	.byte	$02
	.byte	$1E
	.byte	$35
	.byte	$00
	.byte	$02
	.byte	$1A
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$35
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$12
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$35
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$12
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$35
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$12
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$35
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$12
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$35
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$16
	.byte	$35
	.byte	$00
	.byte	$02
	.byte	$1E
	.byte	$35
	.byte	$00
	.byte	$02
	.byte	$34
	.byte	$03
	.byte	$05
	.byte	$12
	.byte	$14
	.byte	$09
	.byte	$06
	.byte	$09
	.byte	$05
	.byte	$04
	.byte	$00
	.byte	$05
	.byte	$14
	.byte	$08
	.byte	$09
	.byte	$03
	.byte	$01
	.byte	$0C
	.byte	$00
	.byte	$08
	.byte	$01
	.byte	$03
	.byte	$0B
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$02
	.byte	$2F
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$24
	.byte	$22
	.byte	$21
	.byte	$1B
	.byte	$20
	.byte	$21
	.byte	$00
	.byte	$02
	.byte	$56
	.byte	$1F
	.byte	$00
	.byte	$08
	.byte	$12
	.byte	$00
	.byte	$05
	.byte	$18
	.byte	$01
	.byte	$0D
	.byte	$00
	.byte	$02
	.byte	$14
	.byte	$1C
	.byte	$1D
	.byte	$20
	.byte	$00
	.byte	$11
	.byte	$15
	.byte	$05
	.byte	$13
	.byte	$14
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$13
	.byte	$00
	.byte	$02
	.byte	$14
	.byte	$16
	.byte	$05
	.byte	$12
	.byte	$13
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$02
	.byte	$71
	.byte	$71
	.byte	$70
	.byte	$80
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$70
	.byte	$71
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$70
	.byte	$81
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$80
	.byte	$81
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$70
	.byte	$80
	.byte	$70
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$02
	.byte	$02
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$80
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$71
	.byte	$71
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$70
	.byte	$80
	.byte	$70
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$71
	.byte	$70
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$81
	.byte	$70
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$70
	.byte	$71
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$71
	.byte	$70
	.byte	$81
	.byte	$80
	.byte	$00
	.byte	$71
	.byte	$70
	.byte	$71
	.byte	$71
	.byte	$00
	.byte	$71
	.byte	$02
	.byte	$02
	.byte	$70
	.byte	$00
	.byte	$70
	.byte	$80
	.byte	$70
	.byte	$71
	.byte	$00
	.byte	$02
	.byte	$B2
	.byte	$05
	.byte	$01
	.byte	$50
	.byte	$05
	.byte	$01
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$01
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$00
	.byte	$02
	.byte	$00
_PAL_SCREEN_CEH:
	.byte	$0F
	.byte	$00
	.byte	$16
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$2D
	.byte	$10
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_OSCP:
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$1F
	.byte	$33
	.byte	$07
	.byte	$1F
	.byte	$00
	.byte	$07
	.byte	$27
	.byte	$72
	.byte	$73
	.byte	$00
	.byte	$07
	.byte	$1D
	.byte	$82
	.byte	$83
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$07
	.byte	$0C
	.byte	$92
	.byte	$93
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$0C
	.byte	$A2
	.byte	$A3
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B4
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$0C
	.byte	$C0
	.byte	$C1
	.byte	$C2
	.byte	$C3
	.byte	$C4
	.byte	$C5
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$07
	.byte	$26
	.byte	$33
	.byte	$07
	.byte	$1F
	.byte	$00
	.byte	$07
	.byte	$06
	.byte	$0F
	.byte	$06
	.byte	$06
	.byte	$05
	.byte	$0E
	.byte	$13
	.byte	$09
	.byte	$16
	.byte	$05
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$03
	.byte	$05
	.byte	$12
	.byte	$14
	.byte	$09
	.byte	$06
	.byte	$09
	.byte	$05
	.byte	$04
	.byte	$00
	.byte	$10
	.byte	$12
	.byte	$0F
	.byte	$06
	.byte	$05
	.byte	$13
	.byte	$13
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$01
	.byte	$0C
	.byte	$00
	.byte	$07
	.byte	$2A
	.byte	$D3
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$0F
	.byte	$13
	.byte	$3F
	.byte	$1C
	.byte	$1B
	.byte	$1C
	.byte	$3F
	.byte	$1B
	.byte	$22
	.byte	$20
	.byte	$23
	.byte	$21
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D8
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$E7
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E0
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$D1
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$E2
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E1
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$E2
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D1
	.byte	$00
	.byte	$00
	.byte	$E4
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D3
	.byte	$00
	.byte	$10
	.byte	$05
	.byte	$0E
	.byte	$05
	.byte	$14
	.byte	$12
	.byte	$01
	.byte	$14
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$14
	.byte	$05
	.byte	$13
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D3
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E3
	.byte	$00
	.byte	$00
	.byte	$D1
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D7
	.byte	$00
	.byte	$07
	.byte	$08
	.byte	$29
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$E4
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D3
	.byte	$00
	.byte	$00
	.byte	$D7
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E8
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$1D
	.byte	$1F
	.byte	$00
	.byte	$08
	.byte	$0F
	.byte	$15
	.byte	$12
	.byte	$00
	.byte	$05
	.byte	$18
	.byte	$01
	.byte	$0D
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$E5
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E1
	.byte	$00
	.byte	$00
	.byte	$E4
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D4
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$D5
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D0
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$E3
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$E7
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D6
	.byte	$00
	.byte	$D2
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$0C
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$12
	.byte	$05
	.byte	$10
	.byte	$0F
	.byte	$12
	.byte	$14
	.byte	$00
	.byte	$01
	.byte	$16
	.byte	$01
	.byte	$09
	.byte	$0C
	.byte	$01
	.byte	$02
	.byte	$0C
	.byte	$05
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D3
	.byte	$00
	.byte	$E6
	.byte	$00
	.byte	$E1
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$15
	.byte	$10
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$12
	.byte	$05
	.byte	$11
	.byte	$15
	.byte	$05
	.byte	$13
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$06
	.byte	$E3
	.byte	$00
	.byte	$D8
	.byte	$00
	.byte	$D8
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$E0
	.byte	$00
	.byte	$07
	.byte	$0D
	.byte	$D1
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D4
	.byte	$00
	.byte	$E4
	.byte	$00
	.byte	$E5
	.byte	$00
	.byte	$00
	.byte	$D1
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D3
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D6
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$E5
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D6
	.byte	$00
	.byte	$E6
	.byte	$00
	.byte	$E7
	.byte	$00
	.byte	$00
	.byte	$E1
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D2
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E4
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$D6
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D7
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D5
	.byte	$00
	.byte	$00
	.byte	$D6
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$E1
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D4
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$E3
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$E7
	.byte	$00
	.byte	$00
	.byte	$E7
	.byte	$00
	.byte	$00
	.byte	$D0
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$D1
	.byte	$00
	.byte	$00
	.byte	$D7
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$E3
	.byte	$00
	.byte	$E5
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D2
	.byte	$00
	.byte	$07
	.byte	$06
	.byte	$D5
	.byte	$00
	.byte	$00
	.byte	$E8
	.byte	$00
	.byte	$07
	.byte	$05
	.byte	$E1
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D1
	.byte	$00
	.byte	$E2
	.byte	$00
	.byte	$07
	.byte	$04
	.byte	$D4
	.byte	$00
	.byte	$07
	.byte	$06
	.byte	$D3
	.byte	$00
	.byte	$00
	.byte	$E2
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$03
	.byte	$03
	.byte	$00
	.byte	$07
	.byte	$0D
	.byte	$C0
	.byte	$C0
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$C0
	.byte	$00
	.byte	$CC
	.byte	$CC
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$CC
	.byte	$CC
	.byte	$3C
	.byte	$0C
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$0C
	.byte	$FF
	.byte	$F3
	.byte	$33
	.byte	$07
	.byte	$02
	.byte	$F0
	.byte	$CC
	.byte	$C0
	.byte	$3F
	.byte	$0F
	.byte	$03
	.byte	$0C
	.byte	$03
	.byte	$0C
	.byte	$00
	.byte	$0C
	.byte	$03
	.byte	$07
	.byte	$00
_PAL_SCREEN_OSCP:
	.byte	$0F
	.byte	$13
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_CCSSA:
	.byte	$07
	.byte	$00
	.byte	$07
	.byte	$61
	.byte	$74
	.byte	$75
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$79
	.byte	$7A
	.byte	$7B
	.byte	$7C
	.byte	$7D
	.byte	$7E
	.byte	$00
	.byte	$07
	.byte	$14
	.byte	$84
	.byte	$85
	.byte	$86
	.byte	$87
	.byte	$88
	.byte	$89
	.byte	$8A
	.byte	$8B
	.byte	$8C
	.byte	$8D
	.byte	$8E
	.byte	$8F
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$94
	.byte	$95
	.byte	$96
	.byte	$97
	.byte	$98
	.byte	$99
	.byte	$9A
	.byte	$9B
	.byte	$9C
	.byte	$9D
	.byte	$9E
	.byte	$9F
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$A4
	.byte	$A5
	.byte	$A6
	.byte	$A7
	.byte	$A8
	.byte	$A9
	.byte	$AA
	.byte	$AB
	.byte	$AC
	.byte	$AD
	.byte	$AE
	.byte	$AF
	.byte	$00
	.byte	$07
	.byte	$13
	.byte	$6B
	.byte	$B5
	.byte	$B6
	.byte	$B7
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$00
	.byte	$BE
	.byte	$BF
	.byte	$00
	.byte	$07
	.byte	$34
	.byte	$03
	.byte	$12
	.byte	$19
	.byte	$10
	.byte	$14
	.byte	$0F
	.byte	$00
	.byte	$07
	.byte	$19
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$12
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$19
	.byte	$00
	.byte	$07
	.byte	$17
	.byte	$03
	.byte	$05
	.byte	$12
	.byte	$14
	.byte	$09
	.byte	$06
	.byte	$09
	.byte	$03
	.byte	$01
	.byte	$14
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$07
	.byte	$12
	.byte	$03
	.byte	$0F
	.byte	$0E
	.byte	$13
	.byte	$0F
	.byte	$12
	.byte	$14
	.byte	$09
	.byte	$15
	.byte	$0D
	.byte	$00
	.byte	$07
	.byte	$57
	.byte	$33
	.byte	$00
	.byte	$0E
	.byte	$0F
	.byte	$0E
	.byte	$10
	.byte	$12
	.byte	$0F
	.byte	$06
	.byte	$09
	.byte	$14
	.byte	$00
	.byte	$16
	.byte	$0F
	.byte	$0C
	.byte	$15
	.byte	$0E
	.byte	$14
	.byte	$05
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$07
	.byte	$2A
	.byte	$33
	.byte	$00
	.byte	$03
	.byte	$12
	.byte	$19
	.byte	$10
	.byte	$14
	.byte	$0F
	.byte	$00
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$12
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$19
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$00
	.byte	$07
	.byte	$07
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$0E
	.byte	$04
	.byte	$01
	.byte	$12
	.byte	$04
	.byte	$00
	.byte	$2A
	.byte	$03
	.byte	$03
	.byte	$13
	.byte	$13
	.byte	$2B
	.byte	$00
	.byte	$07
	.byte	$10
	.byte	$03
	.byte	$0F
	.byte	$0D
	.byte	$0D
	.byte	$09
	.byte	$14
	.byte	$14
	.byte	$05
	.byte	$05
	.byte	$00
	.byte	$0D
	.byte	$05
	.byte	$0D
	.byte	$02
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$07
	.byte	$2D
	.byte	$33
	.byte	$00
	.byte	$01
	.byte	$12
	.byte	$03
	.byte	$08
	.byte	$09
	.byte	$14
	.byte	$05
	.byte	$03
	.byte	$14
	.byte	$00
	.byte	$0F
	.byte	$06
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$13
	.byte	$13
	.byte	$00
	.byte	$07
	.byte	$0E
	.byte	$01
	.byte	$15
	.byte	$04
	.byte	$09
	.byte	$14
	.byte	$0F
	.byte	$12
	.byte	$00
	.byte	$05
	.byte	$18
	.byte	$01
	.byte	$0D
	.byte	$00
	.byte	$2A
	.byte	$03
	.byte	$03
	.byte	$13
	.byte	$13
	.byte	$01
	.byte	$2B
	.byte	$00
	.byte	$07
	.byte	$29
	.byte	$33
	.byte	$00
	.byte	$17
	.byte	$0F
	.byte	$12
	.byte	$0C
	.byte	$04
	.byte	$13
	.byte	$00
	.byte	$06
	.byte	$09
	.byte	$12
	.byte	$13
	.byte	$14
	.byte	$00
	.byte	$03
	.byte	$05
	.byte	$12
	.byte	$14
	.byte	$09
	.byte	$06
	.byte	$09
	.byte	$05
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$09
	.byte	$03
	.byte	$03
	.byte	$13
	.byte	$13
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$04
	.byte	$09
	.byte	$14
	.byte	$0F
	.byte	$12
	.byte	$00
	.byte	$07
	.byte	$CB
	.byte	$00
	.byte	$07
	.byte	$00
_PAL_SCREEN_CCSSA:
	.byte	$0F
	.byte	$21
	.byte	$27
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_ONION:
	.byte	$06
	.byte	$00
	.byte	$06
	.byte	$2C
	.byte	$3C
	.byte	$00
	.byte	$06
	.byte	$1A
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$39
	.byte	$3B
	.byte	$38
	.byte	$39
	.byte	$3A
	.byte	$39
	.byte	$3D
	.byte	$3E
	.byte	$59
	.byte	$5A
	.byte	$00
	.byte	$06
	.byte	$12
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$4B
	.byte	$48
	.byte	$49
	.byte	$4A
	.byte	$4B
	.byte	$4D
	.byte	$4E
	.byte	$69
	.byte	$6A
	.byte	$00
	.byte	$06
	.byte	$1A
	.byte	$5C
	.byte	$5D
	.byte	$00
	.byte	$06
	.byte	$1C
	.byte	$5C
	.byte	$4E
	.byte	$00
	.byte	$06
	.byte	$2D
	.byte	$33
	.byte	$06
	.byte	$1F
	.byte	$00
	.byte	$06
	.byte	$37
	.byte	$C9
	.byte	$CA
	.byte	$00
	.byte	$06
	.byte	$1D
	.byte	$D9
	.byte	$DA
	.byte	$3F
	.byte	$30
	.byte	$3F
	.byte	$6D
	.byte	$00
	.byte	$06
	.byte	$02
	.byte	$4C
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$05
	.byte	$00
	.byte	$09
	.byte	$0E
	.byte	$14
	.byte	$05
	.byte	$12
	.byte	$01
	.byte	$03
	.byte	$14
	.byte	$09
	.byte	$16
	.byte	$05
	.byte	$00
	.byte	$06
	.byte	$03
	.byte	$E9
	.byte	$EA
	.byte	$00
	.byte	$06
	.byte	$02
	.byte	$5E
	.byte	$00
	.byte	$06
	.byte	$03
	.byte	$10
	.byte	$01
	.byte	$19
	.byte	$0D
	.byte	$05
	.byte	$0E
	.byte	$14
	.byte	$13
	.byte	$00
	.byte	$02
	.byte	$05
	.byte	$14
	.byte	$17
	.byte	$05
	.byte	$05
	.byte	$0E
	.byte	$00
	.byte	$06
	.byte	$0A
	.byte	$30
	.byte	$00
	.byte	$06
	.byte	$03
	.byte	$02
	.byte	$09
	.byte	$14
	.byte	$03
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$17
	.byte	$01
	.byte	$0C
	.byte	$0C
	.byte	$05
	.byte	$14
	.byte	$13
	.byte	$00
	.byte	$06
	.byte	$0B
	.byte	$5E
	.byte	$00
	.byte	$06
	.byte	$1D
	.byte	$CB
	.byte	$CC
	.byte	$00
	.byte	$06
	.byte	$1D
	.byte	$DB
	.byte	$DC
	.byte	$00
	.byte	$06
	.byte	$02
	.byte	$4C
	.byte	$02
	.byte	$09
	.byte	$10
	.byte	$3F
	.byte	$22
	.byte	$23
	.byte	$00
	.byte	$10
	.byte	$01
	.byte	$19
	.byte	$0A
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$06
	.byte	$0B
	.byte	$EB
	.byte	$EC
	.byte	$00
	.byte	$06
	.byte	$03
	.byte	$0F
	.byte	$16
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$14
	.byte	$0F
	.byte	$12
	.byte	$00
	.byte	$08
	.byte	$09
	.byte	$04
	.byte	$04
	.byte	$05
	.byte	$0E
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$12
	.byte	$16
	.byte	$09
	.byte	$03
	.byte	$05
	.byte	$13
	.byte	$00
	.byte	$06
	.byte	$46
	.byte	$4C
	.byte	$17
	.byte	$09
	.byte	$0E
	.byte	$0E
	.byte	$05
	.byte	$12
	.byte	$27
	.byte	$00
	.byte	$06
	.byte	$18
	.byte	$0D
	.byte	$09
	.byte	$14
	.byte	$00
	.byte	$1D
	.byte	$1B
	.byte	$1D
	.byte	$1C
	.byte	$00
	.byte	$02
	.byte	$09
	.byte	$14
	.byte	$03
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$08
	.byte	$01
	.byte	$03
	.byte	$0B
	.byte	$01
	.byte	$14
	.byte	$08
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$06
	.byte	$FE
	.byte	$00
	.byte	$06
	.byte	$1A
	.byte	$51
	.byte	$10
	.byte	$00
	.byte	$06
	.byte	$06
	.byte	$51
	.byte	$00
	.byte	$06
	.byte	$06
	.byte	$05
	.byte	$00
	.byte	$06
	.byte	$16
	.byte	$00
	.byte	$06
	.byte	$00
_PAL_SCREEN_ONION:
	.byte	$0F
	.byte	$24
	.byte	$3D
	.byte	$30
	.byte	$0F
	.byte	$28
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_SPEAKING:
	.byte	$0A
	.byte	$00
	.byte	$0A
	.byte	$0D
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$0F
	.byte	$41
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$03
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$0A
	.byte	$06
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$41
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$42
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$41
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$09
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$14
	.byte	$10
	.byte	$15
	.byte	$02
	.byte	$0C
	.byte	$09
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$13
	.byte	$10
	.byte	$05
	.byte	$01
	.byte	$0B
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$40
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$06
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$0A
	.byte	$08
	.byte	$42
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$40
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$41
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$42
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$41
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$0A
	.byte	$19
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$91
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$0F
	.byte	$03
	.byte	$0B
	.byte	$03
	.byte	$08
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$14
	.byte	$12
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$0A
	.byte	$04
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$0F
	.byte	$0E
	.byte	$06
	.byte	$05
	.byte	$12
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$05
	.byte	$2D
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$13
	.byte	$13
	.byte	$01
	.byte	$00
	.byte	$17
	.byte	$0F
	.byte	$12
	.byte	$0B
	.byte	$13
	.byte	$08
	.byte	$0F
	.byte	$10
	.byte	$00
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$08
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$08
	.byte	$41
	.byte	$00
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$41
	.byte	$00
	.byte	$0A
	.byte	$02
	.byte	$90
	.byte	$00
	.byte	$14
	.byte	$12
	.byte	$01
	.byte	$16
	.byte	$05
	.byte	$0C
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$00
	.byte	$14
	.byte	$09
	.byte	$10
	.byte	$13
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$00
	.byte	$0A
	.byte	$05
	.byte	$42
	.byte	$00
	.byte	$0A
	.byte	$1F
	.byte	$90
	.byte	$00
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$03
	.byte	$0B
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$13
	.byte	$01
	.byte	$14
	.byte	$13
	.byte	$00
	.byte	$05
	.byte	$18
	.byte	$14
	.byte	$12
	.byte	$05
	.byte	$0D
	.byte	$05
	.byte	$00
	.byte	$05
	.byte	$14
	.byte	$04
	.byte	$25
	.byte	$00
	.byte	$0A
	.byte	$23
	.byte	$90
	.byte	$00
	.byte	$17
	.byte	$08
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$14
	.byte	$0F
	.byte	$00
	.byte	$04
	.byte	$0F
	.byte	$00
	.byte	$09
	.byte	$06
	.byte	$00
	.byte	$19
	.byte	$0F
	.byte	$15
	.byte	$12
	.byte	$00
	.byte	$0A
	.byte	$0D
	.byte	$0E
	.byte	$01
	.byte	$14
	.byte	$09
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$0E
	.byte	$13
	.byte	$00
	.byte	$02
	.byte	$09
	.byte	$14
	.byte	$03
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$0A
	.byte	$2A
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$14
	.byte	$14
	.byte	$03
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$03
	.byte	$09
	.byte	$14
	.byte	$01
	.byte	$04
	.byte	$05
	.byte	$0C
	.byte	$00
	.byte	$10
	.byte	$0C
	.byte	$01
	.byte	$0E
	.byte	$0E
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$0A
	.byte	$25
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$09
	.byte	$14
	.byte	$03
	.byte	$0F
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$2D
	.byte	$00
	.byte	$14
	.byte	$08
	.byte	$05
	.byte	$00
	.byte	$0A
	.byte	$0A
	.byte	$0E
	.byte	$05
	.byte	$18
	.byte	$14
	.byte	$00
	.byte	$1C
	.byte	$1B
	.byte	$1B
	.byte	$00
	.byte	$19
	.byte	$05
	.byte	$01
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$0A
	.byte	$6D
	.byte	$50
	.byte	$0A
	.byte	$1F
	.byte	$51
	.byte	$0A
	.byte	$5F
	.byte	$55
	.byte	$45
	.byte	$55
	.byte	$45
	.byte	$55
	.byte	$0A
	.byte	$02
	.byte	$15
	.byte	$54
	.byte	$55
	.byte	$7F
	.byte	$53
	.byte	$57
	.byte	$DF
	.byte	$14
	.byte	$54
	.byte	$55
	.byte	$F5
	.byte	$75
	.byte	$7D
	.byte	$FF
	.byte	$FF
	.byte	$55
	.byte	$74
	.byte	$45
	.byte	$FF
	.byte	$0A
	.byte	$04
	.byte	$F4
	.byte	$30
	.byte	$44
	.byte	$FF
	.byte	$0A
	.byte	$04
	.byte	$F3
	.byte	$30
	.byte	$34
	.byte	$FF
	.byte	$0A
	.byte	$03
	.byte	$0F
	.byte	$03
	.byte	$00
	.byte	$F7
	.byte	$F5
	.byte	$0A
	.byte	$02
	.byte	$FF
	.byte	$F5
	.byte	$0A
	.byte	$02
	.byte	$0F
	.byte	$0A
	.byte	$06
	.byte	$0F
	.byte	$0A
	.byte	$00
_PAL_SCREEN_SPEAKING:
	.byte	$0F
	.byte	$24
	.byte	$3D
	.byte	$30
	.byte	$0F
	.byte	$1C
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$07
	.byte	$17
	.byte	$30
_BG_SCREEN_SPEAKING_2:
	.byte	$11
	.byte	$A1
	.byte	$11
	.byte	$19
	.byte	$43
	.byte	$11
	.byte	$02
	.byte	$A1
	.byte	$11
	.byte	$05
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$11
	.byte	$09
	.byte	$43
	.byte	$11
	.byte	$03
	.byte	$A1
	.byte	$11
	.byte	$05
	.byte	$43
	.byte	$11
	.byte	$02
	.byte	$A1
	.byte	$11
	.byte	$06
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$11
	.byte	$07
	.byte	$43
	.byte	$11
	.byte	$07
	.byte	$A1
	.byte	$A1
	.byte	$43
	.byte	$11
	.byte	$03
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$11
	.byte	$05
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$11
	.byte	$06
	.byte	$43
	.byte	$11
	.byte	$02
	.byte	$A1
	.byte	$11
	.byte	$02
	.byte	$43
	.byte	$11
	.byte	$06
	.byte	$3E
	.byte	$3F
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$11
	.byte	$03
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$06
	.byte	$10
	.byte	$15
	.byte	$02
	.byte	$0C
	.byte	$09
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$13
	.byte	$10
	.byte	$05
	.byte	$01
	.byte	$0B
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$11
	.byte	$06
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$05
	.byte	$02
	.byte	$0C
	.byte	$0F
	.byte	$03
	.byte	$0B
	.byte	$03
	.byte	$08
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$16
	.byte	$09
	.byte	$0C
	.byte	$0C
	.byte	$01
	.byte	$07
	.byte	$05
	.byte	$00
	.byte	$11
	.byte	$05
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$A0
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$1D
	.byte	$22
	.byte	$00
	.byte	$32
	.byte	$00
	.byte	$03
	.byte	$12
	.byte	$19
	.byte	$10
	.byte	$14
	.byte	$0F
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$12
	.byte	$05
	.byte	$0E
	.byte	$03
	.byte	$19
	.byte	$00
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$02
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$14
	.byte	$19
	.byte	$00
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$0E
	.byte	$04
	.byte	$01
	.byte	$12
	.byte	$04
	.byte	$00
	.byte	$11
	.byte	$09
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$A0
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$1D
	.byte	$23
	.byte	$00
	.byte	$32
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$03
	.byte	$15
	.byte	$12
	.byte	$09
	.byte	$0E
	.byte	$07
	.byte	$00
	.byte	$14
	.byte	$08
	.byte	$05
	.byte	$00
	.byte	$11
	.byte	$02
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$02
	.byte	$03
	.byte	$0F
	.byte	$13
	.byte	$0D
	.byte	$0F
	.byte	$13
	.byte	$00
	.byte	$11
	.byte	$14
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$A0
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$03
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$1D
	.byte	$24
	.byte	$00
	.byte	$32
	.byte	$00
	.byte	$02
	.byte	$0C
	.byte	$0F
	.byte	$03
	.byte	$0B
	.byte	$03
	.byte	$08
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$11
	.byte	$04
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$02
	.byte	$16
	.byte	$09
	.byte	$0C
	.byte	$0C
	.byte	$01
	.byte	$07
	.byte	$05
	.byte	$00
	.byte	$03
	.byte	$0F
	.byte	$0F
	.byte	$12
	.byte	$07
	.byte	$01
	.byte	$0E
	.byte	$09
	.byte	$1A
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$11
	.byte	$07
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$A1
	.byte	$00
	.byte	$11
	.byte	$1D
	.byte	$A1
	.byte	$11
	.byte	$03
	.byte	$43
	.byte	$11
	.byte	$03
	.byte	$A1
	.byte	$11
	.byte	$0C
	.byte	$62
	.byte	$50
	.byte	$11
	.byte	$02
	.byte	$D0
	.byte	$D1
	.byte	$63
	.byte	$11
	.byte	$02
	.byte	$71
	.byte	$A1
	.byte	$11
	.byte	$02
	.byte	$43
	.byte	$11
	.byte	$04
	.byte	$A1
	.byte	$11
	.byte	$0D
	.byte	$61
	.byte	$51
	.byte	$11
	.byte	$02
	.byte	$D0
	.byte	$D1
	.byte	$53
	.byte	$11
	.byte	$02
	.byte	$70
	.byte	$A1
	.byte	$A1
	.byte	$43
	.byte	$3E
	.byte	$3F
	.byte	$43
	.byte	$43
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$A1
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$A1
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$A1
	.byte	$3E
	.byte	$3F
	.byte	$A1
	.byte	$61
	.byte	$51
	.byte	$72
	.byte	$51
	.byte	$D0
	.byte	$D1
	.byte	$53
	.byte	$73
	.byte	$52
	.byte	$70
	.byte	$A1
	.byte	$A1
	.byte	$43
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$A1
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$A1
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$A1
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$A1
	.byte	$4E
	.byte	$4F
	.byte	$A1
	.byte	$61
	.byte	$51
	.byte	$11
	.byte	$02
	.byte	$D0
	.byte	$D1
	.byte	$53
	.byte	$11
	.byte	$02
	.byte	$70
	.byte	$A1
	.byte	$A1
	.byte	$43
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$A1
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$A1
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$A1
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$A1
	.byte	$5E
	.byte	$5F
	.byte	$A1
	.byte	$61
	.byte	$51
	.byte	$11
	.byte	$02
	.byte	$E0
	.byte	$E1
	.byte	$53
	.byte	$11
	.byte	$02
	.byte	$70
	.byte	$A1
	.byte	$A1
	.byte	$43
	.byte	$A1
	.byte	$11
	.byte	$15
	.byte	$C1
	.byte	$A1
	.byte	$B3
	.byte	$C0
	.byte	$A1
	.byte	$11
	.byte	$04
	.byte	$A2
	.byte	$11
	.byte	$16
	.byte	$C2
	.byte	$A1
	.byte	$B3
	.byte	$C0
	.byte	$A1
	.byte	$11
	.byte	$1D
	.byte	$B3
	.byte	$C0
	.byte	$A1
	.byte	$11
	.byte	$04
	.byte	$B0
	.byte	$11
	.byte	$18
	.byte	$B1
	.byte	$C0
	.byte	$A1
	.byte	$11
	.byte	$04
	.byte	$A3
	.byte	$11
	.byte	$19
	.byte	$A1
	.byte	$11
	.byte	$25
	.byte	$AA
	.byte	$11
	.byte	$07
	.byte	$22
	.byte	$40
	.byte	$5F
	.byte	$53
	.byte	$5C
	.byte	$5F
	.byte	$10
	.byte	$88
	.byte	$EE
	.byte	$55
	.byte	$11
	.byte	$05
	.byte	$99
	.byte	$EE
	.byte	$55
	.byte	$11
	.byte	$05
	.byte	$98
	.byte	$AA
	.byte	$A5
	.byte	$11
	.byte	$03
	.byte	$05
	.byte	$09
	.byte	$8A
	.byte	$AA
	.byte	$11
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$88
	.byte	$FA
	.byte	$11
	.byte	$05
	.byte	$BB
	.byte	$AA
	.byte	$0A
	.byte	$11
	.byte	$06
	.byte	$0A
	.byte	$11
	.byte	$00
_PAL_SCREEN_SPEAKING_2:
	.byte	$0F
	.byte	$17
	.byte	$27
	.byte	$30
	.byte	$0F
	.byte	$29
	.byte	$1A
	.byte	$30
	.byte	$0F
	.byte	$17
	.byte	$1A
	.byte	$28
	.byte	$0F
	.byte	$00
	.byte	$2D
	.byte	$30
_BG_SCREEN_NESDEV:
	.byte	$02
	.byte	$90
	.byte	$02
	.byte	$1B
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$1D
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$07
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$07
	.byte	$00
	.byte	$6E
	.byte	$5B
	.byte	$02
	.byte	$0F
	.byte	$6E
	.byte	$00
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$07
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$0F
	.byte	$6F
	.byte	$00
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$07
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$0E
	.byte	$00
	.byte	$09
	.byte	$0E
	.byte	$14
	.byte	$05
	.byte	$0E
	.byte	$04
	.byte	$0F
	.byte	$00
	.byte	$02
	.byte	$05
	.byte	$6F
	.byte	$00
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$04
	.byte	$A0
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$0E
	.byte	$14
	.byte	$05
	.byte	$12
	.byte	$14
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$0D
	.byte	$05
	.byte	$0E
	.byte	$14
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$A0
	.byte	$A0
	.byte	$B0
	.byte	$B0
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$02
	.byte	$02
	.byte	$A0
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$13
	.byte	$00
	.byte	$19
	.byte	$13
	.byte	$14
	.byte	$05
	.byte	$0D
	.byte	$00
	.byte	$02
	.byte	$07
	.byte	$6F
	.byte	$00
	.byte	$A0
	.byte	$A0
	.byte	$B0
	.byte	$B0
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$02
	.byte	$02
	.byte	$A0
	.byte	$A0
	.byte	$B0
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$16
	.byte	$05
	.byte	$0C
	.byte	$0F
	.byte	$10
	.byte	$0D
	.byte	$05
	.byte	$0E
	.byte	$14
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$6F
	.byte	$00
	.byte	$B0
	.byte	$02
	.byte	$05
	.byte	$90
	.byte	$02
	.byte	$02
	.byte	$A0
	.byte	$A0
	.byte	$B0
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$0F
	.byte	$6F
	.byte	$00
	.byte	$B0
	.byte	$02
	.byte	$05
	.byte	$90
	.byte	$02
	.byte	$02
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$00
	.byte	$6E
	.byte	$5B
	.byte	$02
	.byte	$0F
	.byte	$6E
	.byte	$00
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$04
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$13
	.byte	$90
	.byte	$90
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$04
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$02
	.byte	$16
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$02
	.byte	$04
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$02
	.byte	$16
	.byte	$B0
	.byte	$B0
	.byte	$90
	.byte	$90
	.byte	$00
	.byte	$02
	.byte	$20
	.byte	$6E
	.byte	$5B
	.byte	$02
	.byte	$1B
	.byte	$6E
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$1B
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$3F
	.byte	$00
	.byte	$10
	.byte	$12
	.byte	$0F
	.byte	$07
	.byte	$12
	.byte	$01
	.byte	$0D
	.byte	$0D
	.byte	$05
	.byte	$04
	.byte	$00
	.byte	$29
	.byte	$00
	.byte	$13
	.byte	$05
	.byte	$0C
	.byte	$06
	.byte	$00
	.byte	$14
	.byte	$01
	.byte	$15
	.byte	$07
	.byte	$08
	.byte	$14
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$13
	.byte	$15
	.byte	$0D
	.byte	$0D
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$0F
	.byte	$06
	.byte	$00
	.byte	$1D
	.byte	$1B
	.byte	$1D
	.byte	$1D
	.byte	$00
	.byte	$02
	.byte	$0A
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$1B
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$3F
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$14
	.byte	$0F
	.byte	$00
	.byte	$01
	.byte	$13
	.byte	$0D
	.byte	$00
	.byte	$14
	.byte	$0F
	.byte	$0F
	.byte	$0C
	.byte	$03
	.byte	$08
	.byte	$01
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$1B
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$3F
	.byte	$00
	.byte	$0D
	.byte	$0D
	.byte	$03
	.byte	$00
	.byte	$03
	.byte	$08
	.byte	$09
	.byte	$10
	.byte	$13
	.byte	$05
	.byte	$14
	.byte	$00
	.byte	$10
	.byte	$0C
	.byte	$01
	.byte	$19
	.byte	$13
	.byte	$00
	.byte	$0F
	.byte	$0E
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$05
	.byte	$0D
	.byte	$15
	.byte	$0C
	.byte	$01
	.byte	$14
	.byte	$0F
	.byte	$12
	.byte	$13
	.byte	$00
	.byte	$29
	.byte	$00
	.byte	$08
	.byte	$01
	.byte	$12
	.byte	$04
	.byte	$17
	.byte	$01
	.byte	$12
	.byte	$05
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6F
	.byte	$00
	.byte	$02
	.byte	$1B
	.byte	$6F
	.byte	$00
	.byte	$00
	.byte	$6E
	.byte	$5B
	.byte	$02
	.byte	$1B
	.byte	$6E
	.byte	$00
	.byte	$02
	.byte	$20
	.byte	$90
	.byte	$02
	.byte	$02
	.byte	$A0
	.byte	$A0
	.byte	$90
	.byte	$B0
	.byte	$02
	.byte	$19
	.byte	$A0
	.byte	$02
	.byte	$04
	.byte	$90
	.byte	$02
	.byte	$1A
	.byte	$A0
	.byte	$02
	.byte	$04
	.byte	$90
	.byte	$02
	.byte	$1A
	.byte	$FF
	.byte	$3F
	.byte	$0F
	.byte	$02
	.byte	$03
	.byte	$CF
	.byte	$EE
	.byte	$FF
	.byte	$33
	.byte	$22
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$CC
	.byte	$EE
	.byte	$FF
	.byte	$33
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$CC
	.byte	$EE
	.byte	$0F
	.byte	$02
	.byte	$06
	.byte	$0E
	.byte	$00
	.byte	$02
	.byte	$0F
	.byte	$F0
	.byte	$B0
	.byte	$A0
	.byte	$02
	.byte	$05
	.byte	$0F
	.byte	$02
	.byte	$06
	.byte	$0F
	.byte	$02
	.byte	$00
_PAL_SCREEN_NESDEV:
	.byte	$0F
	.byte	$13
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$17
	.byte	$19
	.byte	$29
_BG_SCREEN_QR:
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$26
	.byte	$13
	.byte	$03
	.byte	$01
	.byte	$0E
	.byte	$00
	.byte	$06
	.byte	$0F
	.byte	$12
	.byte	$00
	.byte	$0C
	.byte	$09
	.byte	$0E
	.byte	$0B
	.byte	$05
	.byte	$04
	.byte	$09
	.byte	$0E
	.byte	$00
	.byte	$02
	.byte	$09
	.byte	$31
	.byte	$02
	.byte	$1A
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$05
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$0B
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$05
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$31
	.byte	$02
	.byte	$06
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$05
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$08
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$31
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$02
	.byte	$31
	.byte	$02
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$02
	.byte	$04
	.byte	$31
	.byte	$02
	.byte	$1A
	.byte	$00
	.byte	$02
	.byte	$61
	.byte	$00
	.byte	$02
	.byte	$00
_PAL_SCREEN_QR:
	.byte	$0F
	.byte	$13
	.byte	$00
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$3C
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29
_BG_SCREEN_END:
	.byte	$03
	.byte	$00
	.byte	$03
	.byte	$8E
	.byte	$F4
	.byte	$F5
	.byte	$00
	.byte	$03
	.byte	$1C
	.byte	$F2
	.byte	$F0
	.byte	$F1
	.byte	$F3
	.byte	$00
	.byte	$03
	.byte	$1C
	.byte	$DF
	.byte	$EF
	.byte	$00
	.byte	$03
	.byte	$1D
	.byte	$BD
	.byte	$CF
	.byte	$00
	.byte	$03
	.byte	$1D
	.byte	$CD
	.byte	$CE
	.byte	$00
	.byte	$03
	.byte	$1D
	.byte	$DD
	.byte	$DE
	.byte	$00
	.byte	$03
	.byte	$1D
	.byte	$ED
	.byte	$EE
	.byte	$00
	.byte	$03
	.byte	$1D
	.byte	$FD
	.byte	$FE
	.byte	$00
	.byte	$03
	.byte	$56
	.byte	$01
	.byte	$00
	.byte	$17
	.byte	$09
	.byte	$0E
	.byte	$0E
	.byte	$05
	.byte	$12
	.byte	$00
	.byte	$09
	.byte	$13
	.byte	$00
	.byte	$19
	.byte	$0F
	.byte	$15
	.byte	$00
	.byte	$03
	.byte	$FE
	.byte	$00
	.byte	$03
	.byte	$EA
	.byte	$80
	.byte	$A0
	.byte	$A0
	.byte	$20
	.byte	$00
	.byte	$20
	.byte	$00
	.byte	$80
	.byte	$A8
	.byte	$02
	.byte	$A8
	.byte	$22
	.byte	$82
	.byte	$A0
	.byte	$A0
	.byte	$00
	.byte	$03
	.byte	$02
	.byte	$88
	.byte	$22
	.byte	$00
	.byte	$80
	.byte	$20
	.byte	$00
	.byte	$03
	.byte	$05
	.byte	$88
	.byte	$22
	.byte	$00
	.byte	$00
	.byte	$2A
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$88
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$03
	.byte	$13
	.byte	$00
	.byte	$03
	.byte	$00
_PAL_SCREEN_END:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$21
	.byte	$31
	.byte	$0F
	.byte	$02
	.byte	$05
	.byte	$25
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$29

.segment	"BSS"

.segment	"ZEROPAGE"
_i:
	.res	1,$00
_j:
	.res	1,$00
_state:
	.res	1,$00
_bg:
	.res	2,$00
_pattern_table:
	.res	1,$00
_ppu_addr:
	.res	2,$00
_ppu_data:
	.res	2,$00
_ppu_data_size:
	.res	1,$00
.segment	"OAM"
_text_sprites:
	.res	4,$00

; ---------------------------------------------------------------
; void __near__ ResetScroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ResetScroll: near

.segment	"CODE"

;
; PPU_SCROLL = 0x00;
;
	lda     #$00
	sta     $2005
;
; PPU_SCROLL = 0x00;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ EnablePPU (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_EnablePPU: near

.segment	"CODE"

;
; PPUCTRL_NMI_ON      ; // enable NMIs
;
	lda     #$80
	sta     _i
;
; if(pattern_table == 0) {
;
	lda     _pattern_table
	bne     L0005
;
; i |= (PPUCTRL_BPATTERN_0 | PPUCTRL_SPATTERN_0);
;
	lda     _i
;
; } else {
;
	jmp     L0004
;
; i |= (PPUCTRL_BPATTERN_1 | PPUCTRL_SPATTERN_1);
;
L0005:	lda     _i
	ora     #$18
L0004:	sta     _i
;
; PPU_CTRL = i;
;
	sta     $2000
;
; PPUMASK_L8_SSHOW ; // show sprites in leftmost 8px
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ DisablePPU (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisablePPU: near

.segment	"CODE"

;
; PPU_CTRL = 0x00;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0x00;
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ WritePPU (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_WritePPU: near

.segment	"CODE"

;
; PPU_ADDRESS = (uint8_t)(ppu_addr >> 8);
;
	lda     _ppu_addr+1
	sta     $2006
;
; PPU_ADDRESS = (uint8_t)(ppu_addr);
;
	lda     _ppu_addr
	sta     $2006
;
; for ( i = 0; i < ppu_data_size; ++i ) {
;
	lda     #$00
	sta     _i
L0007:	lda     _i
	cmp     _ppu_data_size
	bcs     L0003
;
; PPU_DATA = ppu_data[i];
;
	lda     _ppu_data
	ldx     _ppu_data+1
	ldy     _i
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     $2007
;
; for ( i = 0; i < ppu_data_size; ++i ) {
;
	inc     _i
	jmp     L0007
;
; }
;
L0003:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ DrawBackground (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawBackground: near

.segment	"CODE"

;
; PPU_ADDRESS = (uint8_t)(PPU_NAMETABLE_0 >> 8);
;
	lda     #$20
	sta     $2006
;
; PPU_ADDRESS = (uint8_t)(PPU_NAMETABLE_0);
;
	lda     #$00
	sta     $2006
;
; UnRLE(bg);
;
	lda     _bg
	ldx     _bg+1
	jmp     _UnRLE

.endproc

; ---------------------------------------------------------------
; void __near__ InitTitle (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitTitle: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_TITLE;
;
	lda     #$00
	sta     _state
;
; pattern_table = 1;
;
	lda     #$01
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	lda     #$00
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_TITLE;
;
	lda     #>(_PAL_TITLE)
	sta     _ppu_data+1
	lda     #<(_PAL_TITLE)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_TITLE);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_TITLE;
;
	lda     #>(_BG_TITLE)
	sta     _bg+1
	lda     #<(_BG_TITLE)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; FamiToneMusicPlay(SONG_TITLE);
;
	lda     #$00
	jsr     _FamiToneMusicPlay
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenTimeline (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenTimeline: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_TIMELINE;
;
	lda     #$01
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_TIMELINE;
;
	lda     #>(_PAL_SCREEN_TIMELINE)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_TIMELINE)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_TIMELINE);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_TIMELINE;
;
	lda     #>(_BG_SCREEN_TIMELINE)
	sta     _bg+1
	lda     #<(_BG_SCREEN_TIMELINE)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; FamiToneMusicPlay(SONG_SCREEN_1);
;
	lda     #$01
	jsr     _FamiToneMusicPlay
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenOTHEREXP (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenOTHEREXP: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_OTHEREXP;
;
	lda     #$02
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_OTHEREXP;
;
	lda     #>(_PAL_SCREEN_OTHEREXP)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_OTHEREXP)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_OTHEREXP);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_OTHEREXP;
;
	lda     #>(_BG_SCREEN_OTHEREXP)
	sta     _bg+1
	lda     #<(_BG_SCREEN_OTHEREXP)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenCEH (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenCEH: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_CEH;
;
	lda     #$03
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_CEH;
;
	lda     #>(_PAL_SCREEN_CEH)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_CEH)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_CEH);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_CEH;
;
	lda     #>(_BG_SCREEN_CEH)
	sta     _bg+1
	lda     #<(_BG_SCREEN_CEH)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenOSCP (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenOSCP: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_OSCP;
;
	lda     #$04
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_OSCP;
;
	lda     #>(_PAL_SCREEN_OSCP)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_OSCP)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_OSCP);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_OSCP;
;
	lda     #>(_BG_SCREEN_OSCP)
	sta     _bg+1
	lda     #<(_BG_SCREEN_OSCP)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenCCSSA (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenCCSSA: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_CCSSA;
;
	lda     #$05
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_CCSSA;
;
	lda     #>(_PAL_SCREEN_CCSSA)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_CCSSA)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_CCSSA);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_CCSSA;
;
	lda     #>(_BG_SCREEN_CCSSA)
	sta     _bg+1
	lda     #<(_BG_SCREEN_CCSSA)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenONION (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenONION: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_ONION;
;
	lda     #$06
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_ONION;
;
	lda     #>(_PAL_SCREEN_ONION)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_ONION)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_ONION);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_ONION;
;
	lda     #>(_BG_SCREEN_ONION)
	sta     _bg+1
	lda     #<(_BG_SCREEN_ONION)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenQR (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenQR: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_QR;
;
	lda     #$0A
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_QR;
;
	lda     #>(_PAL_SCREEN_QR)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_QR)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_QR);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_QR;
;
	lda     #>(_BG_SCREEN_QR)
	sta     _bg+1
	lda     #<(_BG_SCREEN_QR)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenSPEAKING (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenSPEAKING: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_SPEAKING;
;
	lda     #$07
	sta     _state
;
; pattern_table = 1;
;
	lda     #$01
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	lda     #$00
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_SPEAKING;
;
	lda     #>(_PAL_SCREEN_SPEAKING)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_SPEAKING)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_SPEAKING);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_SPEAKING;
;
	lda     #>(_BG_SCREEN_SPEAKING)
	sta     _bg+1
	lda     #<(_BG_SCREEN_SPEAKING)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenSPEAKING_2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenSPEAKING_2: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_SPEAKING_2;
;
	lda     #$08
	sta     _state
;
; pattern_table = 1;
;
	lda     #$01
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	lda     #$00
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_SPEAKING_2;
;
	lda     #>(_PAL_SCREEN_SPEAKING_2)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_SPEAKING_2)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_SPEAKING_2);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_SPEAKING_2;
;
	lda     #>(_BG_SCREEN_SPEAKING_2)
	sta     _bg+1
	lda     #<(_BG_SCREEN_SPEAKING_2)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenNESDEV (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenNESDEV: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_NESDEV;
;
	lda     #$09
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_NESDEV;
;
	lda     #>(_PAL_SCREEN_NESDEV)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_NESDEV)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_NESDEV);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_NESDEV;
;
	lda     #>(_BG_SCREEN_NESDEV)
	sta     _bg+1
	lda     #<(_BG_SCREEN_NESDEV)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ InitScreenEnd (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_InitScreenEnd: near

.segment	"CODE"

;
; DisablePPU();
;
	jsr     _DisablePPU
;
; state = STATE_SCREEN_END;
;
	lda     #$0B
	sta     _state
;
; pattern_table = 0;
;
	lda     #$00
	sta     _pattern_table
;
; ppu_addr = PPU_PALETTE;
;
	ldx     #$3F
	sta     _ppu_addr
	stx     _ppu_addr+1
;
; ppu_data = PAL_SCREEN_END;
;
	lda     #>(_PAL_SCREEN_END)
	sta     _ppu_data+1
	lda     #<(_PAL_SCREEN_END)
	sta     _ppu_data
;
; ppu_data_size = sizeof(PAL_SCREEN_END);
;
	lda     #$10
	sta     _ppu_data_size
;
; WritePPU();
;
	jsr     _WritePPU
;
; bg = BG_SCREEN_END;
;
	lda     #>(_BG_SCREEN_END)
	sta     _bg+1
	lda     #<(_BG_SCREEN_END)
	sta     _bg
;
; DrawBackground();
;
	jsr     _DrawBackground
;
; FamiToneMusicPlay(SONG_SCREEN_END);
;
	lda     #$04
	jsr     _FamiToneMusicPlay
;
; WaitVBlank();
;
	jsr     _WaitVBlank
;
; EnablePPU();
;
	jmp     _EnablePPU

.endproc

; ---------------------------------------------------------------
; void __near__ HandleInput (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_HandleInput: near

.segment	"CODE"

;
; switch(state) {
;
	lda     _state
;
; }
;
	beq     L0071
	cmp     #$01
	beq     L0079
	cmp     #$02
	jeq     L0081
	cmp     #$03
	jeq     L0089
	cmp     #$04
	jeq     L0091
	cmp     #$05
	jeq     L0099
	cmp     #$06
	jeq     L00A1
	cmp     #$07
	jeq     L00A9
	cmp     #$08
	jeq     L00B1
	cmp     #$09
	jeq     L00B9
	cmp     #$0A
	jeq     L00C1
	cmp     #$0B
	jeq     L00C9
	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0071:	lda     _InputPort1
	and     #$10
	beq     L0075
	lda     _InputPort1Prev
	and     #$10
	bne     L0075
;
; InitScreenTimeline();
;
	jsr     _InitScreenTimeline
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L0075:	lda     _InputPort1
	and     #$80
	beq     L0009
	lda     _InputPort1Prev
	and     #$80
	bne     L0009
;
; InitScreenTimeline();
;
	jsr     _InitScreenTimeline
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0009:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0079:	lda     _InputPort1
	and     #$10
	beq     L007D
	lda     _InputPort1Prev
	and     #$10
	bne     L007D
;
; InitScreenOTHEREXP();
;
	jsr     _InitScreenOTHEREXP
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L007D:	lda     _InputPort1
	and     #$80
	beq     L0012
	lda     _InputPort1Prev
	and     #$80
	bne     L0012
;
; InitScreenOTHEREXP();
;
	jsr     _InitScreenOTHEREXP
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0012:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0081:	lda     _InputPort1
	and     #$10
	beq     L0085
	lda     _InputPort1Prev
	and     #$10
	bne     L0085
;
; InitScreenCEH();
;
	jsr     _InitScreenCEH
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L0085:	lda     _InputPort1
	and     #$80
	beq     L001B
	lda     _InputPort1Prev
	and     #$80
	bne     L001B
;
; InitScreenCEH();
;
	jsr     _InitScreenCEH
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L001B:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0089:	lda     _InputPort1
	and     #$10
	beq     L008D
	lda     _InputPort1Prev
	and     #$10
	bne     L008D
;
; InitScreenOSCP();
;
	jsr     _InitScreenOSCP
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L008D:	lda     _InputPort1
	and     #$80
	beq     L0024
	lda     _InputPort1Prev
	and     #$80
	bne     L0024
;
; InitScreenOSCP();
;
	jsr     _InitScreenOSCP
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0024:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0091:	lda     _InputPort1
	and     #$10
	beq     L0095
	lda     _InputPort1Prev
	and     #$10
	bne     L0095
;
; InitScreenCCSSA();
;
	jsr     _InitScreenCCSSA
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L0095:	lda     _InputPort1
	and     #$80
	beq     L002D
	lda     _InputPort1Prev
	and     #$80
	bne     L002D
;
; InitScreenCCSSA();
;
	jsr     _InitScreenCCSSA
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L002D:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L0099:	lda     _InputPort1
	and     #$10
	beq     L009D
	lda     _InputPort1Prev
	and     #$10
	bne     L009D
;
; InitScreenONION();
;
	jsr     _InitScreenONION
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L009D:	lda     _InputPort1
	and     #$80
	beq     L0036
	lda     _InputPort1Prev
	and     #$80
	bne     L0036
;
; InitScreenONION();
;
	jsr     _InitScreenONION
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0036:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00A1:	lda     _InputPort1
	and     #$10
	beq     L00A5
	lda     _InputPort1Prev
	and     #$10
	bne     L00A5
;
; InitScreenSPEAKING();
;
	jsr     _InitScreenSPEAKING
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00A5:	lda     _InputPort1
	and     #$80
	beq     L003F
	lda     _InputPort1Prev
	and     #$80
	bne     L003F
;
; InitScreenSPEAKING();
;
	jsr     _InitScreenSPEAKING
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L003F:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00A9:	lda     _InputPort1
	and     #$10
	beq     L00AD
	lda     _InputPort1Prev
	and     #$10
	bne     L00AD
;
; InitScreenSPEAKING_2();
;
	jsr     _InitScreenSPEAKING_2
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00AD:	lda     _InputPort1
	and     #$80
	beq     L0048
	lda     _InputPort1Prev
	and     #$80
	bne     L0048
;
; InitScreenSPEAKING_2();
;
	jsr     _InitScreenSPEAKING_2
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0048:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00B1:	lda     _InputPort1
	and     #$10
	beq     L00B5
	lda     _InputPort1Prev
	and     #$10
	bne     L00B5
;
; InitScreenNESDEV();
;
	jsr     _InitScreenNESDEV
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00B5:	lda     _InputPort1
	and     #$80
	beq     L0051
	lda     _InputPort1Prev
	and     #$80
	bne     L0051
;
; InitScreenNESDEV();
;
	jsr     _InitScreenNESDEV
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0051:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00B9:	lda     _InputPort1
	and     #$10
	beq     L00BD
	lda     _InputPort1Prev
	and     #$10
	bne     L00BD
;
; InitScreenQR();
;
	jsr     _InitScreenQR
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00BD:	lda     _InputPort1
	and     #$80
	beq     L005A
	lda     _InputPort1Prev
	and     #$80
	bne     L005A
;
; InitScreenQR();
;
	jsr     _InitScreenQR
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L005A:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00C1:	lda     _InputPort1
	and     #$10
	beq     L00C5
	lda     _InputPort1Prev
	and     #$10
	bne     L00C5
;
; InitScreenEnd();
;
	jsr     _InitScreenEnd
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00C5:	lda     _InputPort1
	and     #$80
	beq     L0063
	lda     _InputPort1Prev
	and     #$80
	bne     L0063
;
; InitScreenEnd();
;
	jsr     _InitScreenEnd
;
; FamiToneSfxPlay(SFX_START);
;
	lda     #$03
	jmp     _FamiToneSfxPlay
;
; break;
;
L0063:	rts
;
; if ((InputPort1 & BUTTON_START) && !(InputPort1Prev & BUTTON_START)) {
;
L00C9:	lda     _InputPort1
	and     #$10
	beq     L00CD
	lda     _InputPort1Prev
	and     #$10
	bne     L00CD
;
; InitTitle();
;
	jsr     _InitTitle
;
; FamiToneSfxPlay(SFX_RING);
;
	lda     #$07
	jsr     _FamiToneSfxPlay
;
; if ((InputPort1 & BUTTON_A) && !(InputPort1Prev & BUTTON_A)) {
;
L00CD:	lda     _InputPort1
	and     #$80
	beq     L006C
	lda     _InputPort1Prev
	and     #$80
	bne     L006C
;
; InitTitle();
;
	jsr     _InitTitle
;
; FamiToneSfxPlay(SFX_RING);
;
	lda     #$07
	jmp     _FamiToneSfxPlay
;
; break;
;
L006C:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Update (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Update: near

.segment	"CODE"

;
; switch(state) {
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; FamiToneInit();
;
	jsr     _FamiToneInit
;
; FamiToneSfxInit();
;
	jsr     _FamiToneSfxInit
;
; InitTitle();
;
	jsr     _InitTitle
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; EnablePPU();
;
	jsr     _EnablePPU
;
; WaitFrame();
;
L0002:	jsr     _WaitFrame
;
; FamiToneUpdate();
;
	jsr     _FamiToneUpdate
;
; HandleInput();
;
	jsr     _HandleInput
;
; ResetScroll();
;
	jsr     _ResetScroll
;
; while (1) {
;
	jmp     L0002

.endproc

